import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
const owner='4e5b6367-9a88-48aa-a330-39b685883840',other='306e5ee1-1562-42ce-a291-524e643a892d',post='20c6fe3a-69ea-4849-8b05-febbf85c9821';
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema extensions;
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create function extensions.digest(bytea,text) returns bytea language sql as $$select sha256($1)$$;
create table users(id uuid primary key,verification_expires_at timestamptz);
create table posts(id uuid primary key,user_id uuid,audience text,is_hidden boolean);
create table admin_user_states(user_id uuid,status text);
create table feature_flags(feature_key text,scope_type text,scope_value text,is_enabled boolean,display_mode text,rollout_percent int);
create table zameel_promotion_settings(id int);
create table zameel_promotion_locations(name text);create table zameel_promotion_universities(name text);
create table zameel_verification_requests(id uuid primary key default gen_random_uuid(),user_id uuid,payment_code text unique,amount_fils int default 1000,wallet_number text,beneficiary text,status text default 'pending',created_at timestamptz default now(),reviewed_at timestamptz,reviewed_by uuid,review_note text,starts_at timestamptz,ends_at timestamptz);
create unique index pending_v on zameel_verification_requests(user_id) where status='pending';
create table zameel_post_promotions(id uuid primary key default gen_random_uuid(),post_id uuid,owner_id uuid,days int,notes text,status text default 'pending',created_at timestamptz default now(),updated_at timestamptz default now(),starts_at timestamptz,ends_at timestamptz,reviewed_by uuid,review_note text,audience_type text,countrywide boolean,target_cities text[],target_universities text[],min_age int,max_age int,target_gender text,payment_code text unique,amount_fils int,wallet_number text,beneficiary text,payment_verified_at timestamptz,payment_verified_by uuid);
create unique index pending_p on zameel_post_promotions(post_id) where status in ('pending','approved');
create table admin_audit_logs(actor_id uuid,action text,resource_type text,resource_id text,details jsonb);
create table notifications(user_id uuid,actor_id uuid,type text,title_ar text,title_en text,body_ar text,body_en text,data jsonb,is_read boolean);
create function zameel_account_can_write() returns boolean language sql as $$select auth.uid() is not null$$;
create function admin_has_permission(text,uuid) returns boolean language sql as $$select $2='${owner}'::uuid$$;
create function admin_can_access_screen(text,uuid) returns boolean language sql as $$select $2='${owner}'::uuid$$;
insert into users values('${owner}',null),('${other}',null);insert into posts values('${post}','${owner}','public',false);
insert into feature_flags values('post_promotions','global','*',true,'enabled',100);
select set_config('request.jwt.claim.sub','${owner}',false);`);
const migrations=new URL('../../supabase/migrations/',import.meta.url);
const file=name=>new URL(name,migrations);
const source=await readFile(file('20261003180005_133_post_promotions.sql'),'utf8');
await db.exec(source.slice(source.indexOf('create or replace function public.zameel_request_promotion'),source.indexOf('create or replace function public.zameel_review_promotion')));
await db.exec(await readFile(file('20261007090001_146_google_play_billing.sql'),'utf8'));
const review=await readFile(file('20261004190001_137_appearance_badges_promotions.sql'),'utf8');
await db.exec(review.slice(review.indexOf('create or replace function public.zameel_review_verification'),review.indexOf('create or replace function public.zameel_trust_view')));
const promotionReview=await readFile(file('20261004100001_135_promotion_targeting_wallet.sql'),'utf8');
await db.exec(promotionReview.slice(promotionReview.indexOf('create or replace function public.zameel_review_promotion('),promotionReview.indexOf('create or replace function public.zameel_save_promotion_wallet')));
const one=async(sql,args=[]) => (await db.query(sql,args)).rows[0];
const rpc=async(sql,args=[]) => (await one(sql,args)).result;
const request=await rpc('select zameel_play_request_verification() result');assert.equal(request.payment_source,'google_play');
const intent=await rpc('select zameel_play_prepare_intent($1,$2,$3) result',[owner,'verification',request.id]);assert.equal(intent.product_id,'zameel_verification_month');
await assert.rejects(rpc('select zameel_play_prepare_intent($1,$2,$3) result',[other,'verification',request.id]),/payment_request_unavailable/);
const approve=()=>rpc('select zameel_review_verification($1,$2,$3,$4,$5,$6) result',[owner,request.id,'approve',request.payment_code,1000,'review approved']);
await assert.rejects(approve(),/google_payment_confirmation_required/);assert.equal((await one('select verification_expires_at from users where id=$1',[owner])).verification_expires_at,null);
const record=async(i,hash='a'.repeat(64),actor=owner)=>rpc('select zameel_play_record_verified_purchase($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) result',[actor,i.id,hash,i.product_id,i.account_binding,i.intent_binding,new Date().toISOString(),'GPA.fixture',true,'encrypted-fixture']);
await record(intent);await record(intent);assert.equal((await one('select count(*)::int n from zameel_play_purchase_ledger')).n,1);
await assert.rejects(record(intent,'a'.repeat(64),other),/payment_binding_mismatch/);
await assert.rejects(record(intent,'b'.repeat(64)),/unique constraint/);
await assert.rejects(approve(),/google_payment_confirmation_required/);
await db.query("update zameel_play_purchase_ledger set acknowledgement_state='completed' where intent_id=$1",[intent.id]);
await approve();const expiry=(await one('select verification_expires_at from users where id=$1',[owner])).verification_expires_at;await approve();assert.deepEqual((await one('select verification_expires_at from users where id=$1',[owner])).verification_expires_at,expiry);
const renewal=await rpc('select zameel_play_request_verification() result');
const renewalIntent=await rpc('select zameel_play_prepare_intent($1,$2,$3) result',[owner,'verification',renewal.id]);
await record(renewalIntent,'d'.repeat(64));await db.query("update zameel_play_purchase_ledger set acknowledgement_state='completed' where intent_id=$1",[renewalIntent.id]);
await rpc('select zameel_review_verification($1,$2,$3,$4,$5,$6) result',[owner,renewal.id,'approve',renewal.payment_code,1000,'renewal approved']);
await db.query("select zameel_play_revoke($1,'revoked')",['a'.repeat(64)]);
const remainingDays=(new Date((await one('select verification_expires_at from users where id=$1',[owner])).verification_expires_at)-Date.now())/86400000;
assert.ok(remainingDays>27&&remainingDays<32,'Refund closes first term gap and preserves only the other paid month');
await db.query("select zameel_play_revoke($1,'revoked')",['a'.repeat(64)]);
await db.query("select zameel_play_revoke($1,'revoked')",['d'.repeat(64)]);
assert.equal((await one('select verification_expires_at from users where id=$1',[owner])).verification_expires_at,null);
const promo=await rpc("select zameel_play_request_promotion($1,7,'general',true,'{}','{}',18,100,'both','') result",[post]);
const pi=await rpc('select zameel_play_prepare_intent($1,$2,$3) result',[owner,'promotion',promo.id]);assert.equal(pi.product_id,'zameel_promotion_07_days');
await db.query("update zameel_post_promotions set status='rejected' where id=$1",[promo.id]);
assert.equal((await record(pi,'c'.repeat(64))).settlement_state,'refund_required');
await db.query("select zameel_play_revoke($1,'refunded')",['c'.repeat(64)]);assert.equal((await one('select settlement_state from zameel_play_purchase_ledger where token_sha256=$1',['c'.repeat(64)])).settlement_state,'refunded');
const promo2=await rpc("select zameel_play_request_promotion($1,3,'general',true,'{}','{}',18,100,'both','') result",[post]);
const pi2=await rpc('select zameel_play_prepare_intent($1,$2,$3) result',[owner,'promotion',promo2.id]);
const approvePromo=()=>rpc('select zameel_review_promotion_v2($1,$2,$3,$4,$5,$6) result',[owner,promo2.id,'approve','approved by review',promo2.payment_code,promo2.amount_fils]);
await assert.rejects(approvePromo(),/google_payment_confirmation_required/);
assert.equal((await one('select payment_verified_at from zameel_post_promotions where id=$1',[promo2.id])).payment_verified_at,null);
await record(pi2,'e'.repeat(64));await db.query("update zameel_play_purchase_ledger set acknowledgement_state='completed' where intent_id=$1",[pi2.id]);
await approvePromo();assert.equal((await one('select status from zameel_post_promotions where id=$1',[promo2.id])).status,'approved');
await db.query("select zameel_play_revoke($1,'revoked')",['e'.repeat(64)]);
assert.equal((await one('select status from zameel_post_promotions where id=$1',[promo2.id])).status,'cancelled');
await assert.rejects(approvePromo(),/promotion_already_decided/);
await db.exec('set role authenticated');await assert.rejects(db.query('select * from zameel_play_purchase_ledger'),/permission denied/);await assert.rejects(db.query('select zameel_play_prepare_intent($1,$2,$3)',[owner,'verification',request.id]),/permission denied/);await db.exec('reset role');
console.log('PASS: PostgreSQL migration; owner binding; replay protection; approval rollback before paid/consumed; idempotent approval; revocation; late payment refund; client privilege denial.');await db.close();
