import {PGlite} from '@electric-sql/pglite';import fs from 'node:fs';import assert from 'node:assert/strict';
const db=new PGlite(),a='10000000-0000-4000-8000-000000000001',b='10000000-0000-4000-8000-000000000002',c='10000000-0000-4000-8000-000000000003',d='20000000-0000-4000-8000-000000000001',g='20000000-0000-4000-8000-000000000002';
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
create table users(id uuid primary key,name text,profile_image text,account_type text,role text,university text,college text,department text);
create table zameel_registration_profiles(user_id uuid primary key,account_type text,university text,college text,major text,updated_at timestamptz);
create table conversations(id uuid primary key,is_group boolean);
create table conversation_members(conversation_id uuid,user_id uuid);
create table messages(conversation_id uuid,created_at timestamptz);
create table friend_requests(sender_id uuid,receiver_id uuid,status text);
create function zameel_account_can_write() returns boolean language sql as $$select auth.uid() is not null$$;
create function is_blocked(uuid,uuid) returns boolean language sql as $$select false$$;
create function is_conversation_member(uuid,uuid) returns boolean language sql as $$select exists(select 1 from public.conversation_members where conversation_id=$1 and user_id=$2)$$;
insert into users values('${a}','A',null,'student','student','UU','CC','MM'),('${b}','B',null,'general','visitor','','',''),('${c}','C',null,'general','visitor','','','');
insert into zameel_registration_profiles values('${a}','student','UU','CC','MM',now());
insert into conversations values('${d}',false),('${g}',true);
insert into conversation_members values('${d}','${a}'),('${d}','${b}'),('${g}','${a}'),('${g}','${c}');
insert into messages values('${d}',now());select set_config('test.uid','${a}',false);`);
await db.exec(fs.readFileSync(new URL('../supabase/migrations/20261010160001_151_account_chat.sql',import.meta.url),'utf8'));
const query=async(s,args=[]) =>(await db.query(s,args)).rows[0];
await db.query("select zameel_update_academic_status('graduate','UU','CC','MM')");assert.equal((await query('select role from users where id=$1',[a])).role,'visitor');assert.equal((await query("select can_access_community_scope('faculty','UU','CC',null) x")).x,false);
await db.query("select zameel_update_academic_status('general')");assert.equal((await query('select university from users where id=$1',[a])).university,'');assert.equal((await query('select university from zameel_registration_profiles where user_id=$1',[a])).university,'UU');
await assert.rejects(db.query("select zameel_update_academic_status('student','','','')"),/academic_details_required/);
const inbox=(await query('select zameel_chat_inbox() x')).x;assert.equal(inbox.length,1);assert.equal(inbox[0].id,b);
await db.query('select zameel_chat_typing_set($1,true)',[d]);await db.query("select set_config('test.uid',$1,false)",[b]);assert.equal((await query('select zameel_chat_typing_get($1) x',[d])).x,true);
await db.query("update zameel_chat_typing set expires_at=now()-interval '1 second'");assert.equal((await query('select zameel_chat_typing_get($1) x',[d])).x,false);
await db.query("select set_config('test.uid',$1,false)",[c]);await assert.rejects(db.query('select zameel_chat_typing_set($1,true)',[d]),/conversation_access_denied/);
await db.exec('set role authenticated');await assert.rejects(db.query('select * from zameel_chat_typing'),/permission denied/);await assert.rejects(db.query('select * from zameel_academic_changes'),/permission denied/);await db.exec('reset role');
await db.exec(`create table study_files(id int);alter table study_files enable row level security;create policy baseline_read on study_files for select to authenticated using(true);create schema storage;create table storage.objects(id int,bucket_id text);alter table storage.objects enable row level security;create policy baseline_read on storage.objects for select to authenticated using(true);grant select on study_files,users,storage.objects to authenticated;grant usage on schema auth,storage to authenticated;insert into study_files values(1);insert into storage.objects values(1,'study_files'),(2,'other');`);
await db.exec(fs.readFileSync(new URL('../supabase/migrations/20261010160005_151_graduate_access.sql',import.meta.url),'utf8'));
await db.query("select set_config('test.uid',$1,false)",[a]);await db.query("select zameel_update_academic_status('graduate','UU','CC','MM')");await db.exec('set role authenticated');assert.equal((await db.query('select * from study_files')).rows.length,0);assert.equal((await db.query('select * from storage.objects')).rows.length,1);await db.exec('reset role');
console.log('PASS: graduate/general transitions, academic preservation, direct-only inbox, typing membership/expiry and private tables.');await db.close();
