import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
const a='10000000-0000-4000-8000-000000000001', b='10000000-0000-4000-8000-000000000002', stranger='10000000-0000-4000-8000-000000000003';
const c='20000000-0000-4000-8000-000000000001',g='20000000-0000-4000-8000-000000000002';
const device='40000000-0000-4000-8000-000000000001',device2='40000000-0000-4000-8000-000000000002', foreign='40000000-0000-4000-8000-000000000003';
const m='30000000-0000-4000-8000-000000000001',notice='50000000-0000-4000-8000-000000000001';
await db.exec(`create role anon; create role authenticated; create role service_role; create schema auth;
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
create table auth.users(id uuid primary key);insert into auth.users values('${a}'),('${b}'),('${stranger}');
create table users(id uuid primary key,name text,profile_image text,account_type text,role text,university text,college text,department text);
create table zameel_registration_profiles(user_id uuid primary key,account_type text,university text,college text,major text,updated_at timestamptz);
create table conversations(id uuid primary key,is_group boolean);
create table conversation_members(conversation_id uuid,user_id uuid);
create table messages(id uuid primary key default gen_random_uuid(),conversation_id uuid references conversations(id),sender_id uuid references users(id),created_at timestamptz default now(),is_read boolean default false,read_at timestamptz,delivered_at timestamptz);
create table posts(id uuid primary key,user_id uuid references users(id));
create table friend_requests(sender_id uuid,receiver_id uuid,status text);
create table user_blocks(actor uuid,target uuid);
create function is_blocked(uuid,uuid) returns boolean language sql as $$select exists(select 1 from public.user_blocks where actor=$1 and target=$2 or actor=$2 and target=$1)$$;
create function zameel_account_can_write() returns boolean language sql as $$select auth.uid() is not null$$;
create function zameel_account_can_read() returns boolean language sql as $$select auth.uid() is not null and coalesce(current_setting('test.allowed',true),'true')<>'false'$$;
create function is_conversation_member(uuid,uuid) returns boolean language sql as $$select exists(select 1 from public.conversation_members where conversation_id=$1 and user_id=$2)$$;
create table push_device_tokens(id uuid primary key,user_id uuid,token text unique);
create table notifications(id uuid primary key,user_id uuid,type text,data jsonb,is_read boolean default false);
create table zameel_hidden_messages(user_id uuid,message_id uuid);
create table zameel_deleted_messages(message_id uuid);
insert into users values('${a}','A',null,'student','student','UU','CC','MM'),('${b}','B',null,'general','visitor','','',''),('${stranger}','C',null,'general','visitor','','','');
insert into conversations values('${c}',false),('${g}',true);
insert into conversation_members values('${c}','${a}'),('${c}','${b}'),('${g}','${a}'),('${g}','${b}');
insert into push_device_tokens values('${device}','${a}','token-a'),('${device2}','${a}','token-a2'),('${foreign}','${b}','token-b');
select set_config('test.uid','${a}',false);`);
const legacy=fs.readFileSync(new URL('../supabase/migrations/20261010160001_151_account_chat.sql',import.meta.url),'utf8');
await db.exec(legacy);
const receipts=fs.readFileSync(new URL('../supabase/migrations/047_calls_receipts_meet_world.sql',import.meta.url),'utf8');
await db.exec(receipts.slice(receipts.indexOf('create or replace function public.mark_conversation_read'),receipts.indexOf('alter table public.meet_colleague_requests')));
const migration=fs.readFileSync(new URL('../supabase/migrations/20261011000001_153_chat_visibility.sql',import.meta.url),'utf8');
await db.exec(migration);await db.exec(migration);
const scalar=async(sql,args=[]) => Object.values((await db.query(sql,args)).rows[0])[0];
await db.query('insert into messages(id,conversation_id,sender_id) values($1,$2,$3)',[m,c,b]);
await db.query('insert into notifications values($1,$2,\'message\',$3,false)',[notice,a,{conversation_id:c,message_id:m}]);
await db.exec(`insert into messages(conversation_id,sender_id) values('${c}','${b}'),('${c}','${a}'),('${g}','${b}');`);
assert.equal((await scalar('select zameel_chat_inbox_153()'))[0].unread_count,2);
assert.equal('unread_count' in (await scalar('select zameel_chat_inbox()'))[0],false);
await db.query('insert into zameel_hidden_messages values($1,$2)',[a,m]);
assert.equal((await scalar('select zameel_chat_inbox_153()'))[0].unread_count,1);
await db.exec('delete from zameel_hidden_messages');
await db.query('insert into zameel_deleted_messages values($1)',[m]);
assert.equal((await scalar('select zameel_chat_inbox_153()'))[0].unread_count,1);
await db.exec('delete from zameel_deleted_messages');
await db.query('select zameel_chat_device_visibility_153($1,$2)',['token-a',c]);
assert.equal(await scalar('select zameel_chat_should_suppress_push_153($1,$2)',[notice,device]),true);
assert.equal(await scalar('select zameel_chat_should_suppress_push_153($1,$2)',[notice,device2]),false);
assert.equal(await scalar('select zameel_chat_should_suppress_push_153($1,$2)',[notice,foreign]),false);
await db.exec("update zameel_chat_device_visibility_153 set expires_at=now()-interval '1 second'");
assert.equal(await scalar('select zameel_chat_should_suppress_push_153($1,$2)',[notice,device]),false);
await db.query('select zameel_chat_device_visibility_153($1,$2)',['token-a',c]);
await db.query('select zameel_chat_device_visibility_153($1,null)',['token-a']);
assert.equal(await scalar('select count(*)::int from zameel_chat_device_visibility_153'),0);
await assert.rejects(db.query('select zameel_chat_device_visibility_153($1,$2)',['token-b',c]),/device_access_denied/);
await db.query("select set_config('test.uid',$1,false)",[stranger]);
await assert.rejects(db.query('select zameel_chat_mark_read_153($1)',[c]),/conversation_access_denied/);
await db.query("select set_config('test.uid',$1,false)",[a]);
await db.exec(`insert into user_blocks values('${a}','${b}')`);
await assert.rejects(db.query('select zameel_chat_device_visibility_153($1,$2)',['token-a',c]),/conversation_access_denied/);
assert.deepEqual(await scalar('select zameel_chat_inbox_153()'),[]);
await db.exec('delete from user_blocks');
assert.equal(await scalar('select zameel_chat_mark_read_153($1)',[c]),2);
assert.equal((await scalar('select zameel_chat_inbox_153()'))[0].unread_count,0);
assert.equal(await scalar('select is_read from notifications where id=$1',[notice]),true);
assert.equal(await scalar('select zameel_chat_should_suppress_push_153($1,$2)',[notice,device2]),false); // Reading elsewhere never silences an inactive/older client.
await db.query("select set_config('test.allowed','false',false)");
await assert.rejects(db.query('select zameel_chat_inbox_153()'),/account_access_denied/);
await db.query("select set_config('test.allowed','true',false)");
await db.exec('grant usage on schema auth to authenticated; set role authenticated');
await assert.rejects(db.query('select * from zameel_chat_device_visibility_153'),/permission denied/);
await assert.rejects(db.query('select zameel_chat_should_suppress_push_153($1,$2)',[notice,device]),/permission denied/);
await db.exec('reset role;set role service_role');
assert.equal(await scalar('select zameel_chat_should_suppress_push_153($1,$2)',[notice,device]),false);
await db.exec('reset role');
const keys=(await db.query(`select a.attname from pg_constraint c join pg_attribute a on a.attrelid=c.conrelid and a.attnum=any(c.conkey) where c.conrelid='public.zameel_chat_device_visibility_153'::regclass and c.contype='p'`)).rows;
assert.deepEqual(keys.map(x=>x.attname),['id']);
assert.equal((await db.query("select count(*)::int n from pg_constraint where contype='f' and conrelid='posts'::regclass and confrelid='users'::regclass")).rows[0].n,1);
console.log('PASS: actual 153 SQL twice; unread isolation/read reset/hidden/deleted/group exclusions; legacy inbox preserved; per-device visible/expired/closed decisions with older-client delivery preserved; foreign token/nonmember/blocked/suspended denial; service-only push check; surrogate PK and original author FK preserved.');
await db.close();
