import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
const a='10000000-0000-4000-8000-000000000001',b='10000000-0000-4000-8000-000000000002',c='10000000-0000-4000-8000-000000000003';
const chat='20000000-0000-4000-8000-000000000001',other='20000000-0000-4000-8000-000000000002',m='30000000-0000-4000-8000-000000000001',own='30000000-0000-4000-8000-000000000002',post='40000000-0000-4000-8000-000000000001';
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;
create table auth.users(id uuid primary key);create table users(id uuid primary key,name text);
create table posts(id uuid primary key,user_id uuid references users(id));
create table conversations(id uuid primary key,is_group boolean default false);
create table conversation_members(conversation_id uuid,user_id uuid);
create table messages(id uuid primary key,conversation_id uuid references conversations(id),sender_id uuid references users(id));
create table user_blocks(blocker_id uuid,blocked_id uuid);
create table zameel_hidden_messages(user_id uuid,message_id uuid);
create table zameel_deleted_messages(message_id uuid);
create table zameel_like_notified(post_id uuid references posts(id),actor_id uuid references users(id),owner_id uuid references users(id),primary key(post_id,actor_id,owner_id));
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
create function is_conversation_member(target_conversation_id uuid,target_user_id uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.conversation_members where conversation_id=target_conversation_id and user_id=target_user_id)$$;
create function is_blocked(a uuid,b uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.user_blocks where (blocker_id=a and blocked_id=b) or (blocker_id=b and blocked_id=a))$$;
create function zameel_account_can_write() returns boolean language sql stable as $$select coalesce(current_setting('test.allowed',true),'true')<>'false'$$;
create function zameel_account_can_read() returns boolean language sql stable as $$select true$$;
insert into auth.users values('${a}'),('${b}'),('${c}');insert into users values('${a}','A'),('${b}','B'),('${c}','C');
insert into posts values('${post}','${a}');insert into zameel_like_notified values('${post}','${b}','${a}');
insert into conversations values('${chat}',false),('${other}',false);insert into conversation_members values('${chat}','${a}'),('${chat}','${b}'),('${other}','${c}');
insert into messages values('${m}','${chat}','${b}'),('${own}','${chat}','${a}');`);
const migration=fs.readFileSync(new URL('../supabase/migrations/20261010190001_152_chat_reactions.sql',import.meta.url),'utf8');
await db.exec(migration);await db.exec(migration);
const scalar=async sql=>(await db.query(sql)).rows[0];
assert.equal((await scalar('select count(*)::int n from zameel_like_notified')).n,1);
await db.query('insert into zameel_like_notified(post_id,actor_id,owner_id) values($1,$2,$3) on conflict do nothing',[post,b,a]);
assert.equal((await scalar('select count(*)::int n from zameel_like_notified')).n,1);
// The PK is independent of every foreign key: neither history table can be
// inferred as a junction by PostgREST, and the original author join is intact.
for(const table of ['zameel_like_notified','zameel_message_reactions']){
 const keys=await db.query(`select conkey from pg_constraint where conrelid=$1::regclass and contype='p'`,[table]);
 const fks=await db.query(`select conkey from pg_constraint where conrelid=$1::regclass and contype='f'`,[table]);
 const all=new Set(fks.rows.flatMap(r=>r.conkey));assert(keys.rows[0].conkey.every(k=>!all.has(k)));
}
assert.equal((await scalar("select count(*)::int n from posts join users on users.id=posts.user_id")).n,1);
await db.query("select set_config('test.uid',$1,false)",[a]);
await db.query('select zameel_message_react($1,$2,$3)',[chat,m,'❤️']);
let rows=(await db.query('select zameel_message_reactions_get($1,$2) r',[chat,[m]])).rows[0].r;
assert.equal(rows.length,1);assert.equal(rows[0].user_id,a);
await db.query('select zameel_message_react($1,$2,$3)',[chat,m,'😂']);
assert.equal((await scalar('select count(*)::int n from zameel_message_reactions')).n,1);
await db.query("select set_config('test.uid',$1,false)",[b]);
rows=(await db.query('select zameel_message_reactions_get($1,$2) r',[chat,[m]])).rows[0].r;assert.equal(rows[0].emoji,'😂');
await assert.rejects(db.query('select zameel_message_react($1,$2,$3)',[chat,m,'🙏']),/message_access_denied/);
await db.query("select set_config('test.uid',$1,false)",[a]);
await assert.rejects(db.query('select zameel_message_react($1,$2,$3)',[chat,m,'x']),/invalid_reaction/);
await assert.rejects(db.query('select zameel_message_react($1,$2,$3)',[other,m,'❤️']),/conversation_access_denied/);
await db.query("select set_config('test.uid',$1,false)",[c]);
await assert.rejects(db.query('select zameel_message_reactions_get($1,$2)',[chat,[m]]),/conversation_access_denied/);
await db.query("select set_config('test.uid',$1,false)",[a]);
await db.exec(`insert into user_blocks values('${a}','${b}');`);
await assert.rejects(db.query('select zameel_message_react($1,$2,$3)',[chat,m,'❤️']),/message_access_denied/);
assert.deepEqual((await db.query('select zameel_message_reactions_get($1,$2) r',[chat,[m]])).rows[0].r,[]);
await db.exec('delete from user_blocks');
await db.exec(`insert into zameel_hidden_messages values('${a}','${m}')`);
await assert.rejects(db.query('select zameel_message_react($1,$2,$3)',[chat,m,'❤️']),/message_access_denied/);
await db.exec('delete from zameel_hidden_messages');
await db.exec(`insert into zameel_deleted_messages values('${m}')`);
await assert.rejects(db.query('select zameel_message_react($1,$2,$3)',[chat,m,'❤️']),/message_access_denied/);
await db.exec('delete from zameel_deleted_messages');
await db.query("select set_config('test.allowed','false',false)");
await assert.rejects(db.query('select zameel_message_react($1,$2,$3)',[chat,m,'❤️']),/conversation_access_denied/);
await db.query("select set_config('test.allowed','true',false)");
await db.query('select zameel_message_react($1,$2,null)',[chat,m]);
assert.equal((await scalar('select count(*)::int n from zameel_message_reactions')).n,0);
await assert.rejects(db.query('select zameel_message_reactions_get($1,$2)',[chat,Array(101).fill(m)]),/reaction_batch_too_large/);
// Execute the existing 151 like trigger against the upgraded history table.
await db.exec(`create table likes(post_id uuid,user_id uuid);
create table notifications(id uuid default gen_random_uuid(),user_id uuid,actor_id uuid,type text,title_ar text,title_en text,body_ar text,body_en text,data jsonb);`);
const legacy=fs.readFileSync(new URL('../supabase/migrations/20261010160004_151_like_notifications.sql',import.meta.url),'utf8');
await db.exec(legacy.slice(legacy.indexOf('create or replace function public.notify_on_like()'),legacy.indexOf('create or replace function public.zameel_cancel_like_alert()')));
await db.exec('create trigger like_alert after insert on likes for each row execute function notify_on_like()');
const nextPost='40000000-0000-4000-8000-000000000002';
await db.query('insert into posts values($1,$2)',[nextPost,a]);
await db.query('insert into likes values($1,$2)',[nextPost,b]);
await db.query('delete from likes where post_id=$1',[nextPost]);
await db.query('insert into likes values($1,$2)',[nextPost,b]);
assert.equal((await scalar("select count(*)::int n from notifications where type='post_like'")).n,1);
await db.exec('set role authenticated');await assert.rejects(db.query('select * from zameel_message_reactions'),/permission denied/);await db.exec('reset role');
console.log('PASS: actual 152 migration twice; legacy author embedding structure; preserved history and deduplication; reactions change/remove and both participants; nonmembers, own/foreign/hidden/deleted messages, blocked/suspended actors and oversized reads denied; private storage.');
await db.close();
