import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';import assert from 'node:assert/strict';
const db=new PGlite();
const ids=['10000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000003'];
await db.exec(`create role anon;create role authenticated;create role service_role;
create schema auth;create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
create table auth.users(id uuid primary key,email text,phone text,email_confirmed_at timestamptz,phone_confirmed_at timestamptz,raw_user_meta_data jsonb default '{}'::jsonb);
create table public.users(id uuid primary key references auth.users(id),name text,email text,phone text,role text default 'student',university text default '',college text default '',department text default '',academic_year text,gender text,display_name_format text,onboarding_complete boolean default true,profile_image text);
create table public.zameel_registration_profiles(user_id uuid primary key,first_name text,father_name text,family_name text,display_name_format text,phone text,email text,verification_method text,email_verified boolean,phone_verified boolean,university text not null,college text not null,major text not null,academic_year text not null,gender text,onboarding_complete boolean,updated_at timestamptz);
create table feature_flags(feature_key text primary key,name_ar text,description text,is_enabled boolean,display_mode text,rollout_percent integer,scope_type text,scope_value text);
create table zameel_quiz_questions(id uuid primary key default gen_random_uuid(),question_ar text,question_en text,options_ar jsonb,options_en jsonb,correct_index smallint,status text);
create table admin_user_states(user_id uuid,status text,suspended_until timestamptz);
create table admin_permissions(permission_key text primary key,name_ar text,category text);
create table admin_roles(id uuid primary key,role_key text);
create table admin_role_permissions(role_id uuid,permission_key text,unique(role_id,permission_key));
create table admin_audit_logs(actor_id uuid,action text,resource_type text,resource_id text,details jsonb);
create function zameel_account_can_write() returns boolean language sql as $$select auth.uid() is not null$$;
create function is_blocked(uuid,uuid) returns boolean language sql as $$select false$$;
create function admin_has_permission(text,uuid) returns boolean language sql as $$select $2='${ids[2]}'::uuid$$;
create function admin_can_access_screen(text,uuid) returns boolean language sql as $$select $2='${ids[2]}'::uuid$$;
insert into auth.users(id,email,phone,email_confirmed_at,phone_confirmed_at) values('${ids[0]}','one@example.com',null,now(),null),('${ids[1]}','two@example.com',null,now(),null),('${ids[2]}','admin@example.com',null,now(),null);
insert into public.users(id,name,email) select id,email,email from auth.users;
insert into zameel_quiz_questions(question_ar,question_en,options_ar,options_en,correct_index,status)
select 'سؤال '||i,'Question '||i,'["a","b","c","d"]','["a","b","c","d"]',0,'published' from generate_series(1,20) i;`);
for (const name of ['20261003180001_133_open_registration.sql','20261003180002_133_trust_game.sql','20261003180003_133_trust_administration.sql']){
 await db.exec(fs.readFileSync(new URL('../supabase/migrations/'+name,import.meta.url),'utf8'));console.log('installed',name);
}
const as=async(i)=>db.query("select set_config('test.uid',$1,false)",[ids[i]]);
const call=async(name,args=[])=>{let r=await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) as result`,args);return r.rows[0].result;};
const bal=async(i)=>Number((await db.query('select balance from zameel_coin_wallets where user_id=$1',[ids[i]])).rows[0].balance);
let passed=0;const check=(x,msg)=>{assert.ok(x,msg);passed++;console.log('PASS',msg);};
async function reset(){await db.exec('delete from zameel_trust_active;delete from zameel_trust_queue;delete from zameel_trust_matches;delete from zameel_coin_ledger;delete from zameel_coin_wallets;update zameel_trust_settings set last_sweep_at=now(),initial_coins=1000,stake=50,reward_unit=10;');}
async function start(){await as(0);let a=await call('zameel_trust_join');check(a.phase==='waiting','first participant queued');await as(1);let b=await call('zameel_trust_join');check(b.phase==='questions'&&await bal(0)===950&&await bal(1)===950,'match reserves exactly 50 each');return b.match_id;}
async function full(mid){for(let n=1;n<=10;n++){await as(0);await call('zameel_trust_answer',[mid,n,0]);await as(1);let r=await call('zameel_trust_answer',[mid,n,0]);assert.equal(r.prize,n*(n+1)*5);}await as(0);return call('zameel_trust_state',[mid]);}
await as(0);await db.query('update users set onboarding_complete=false where id=$1',[ids[0]]);
const data={account_type:'general',first_name:'محمد',father_name:'أحمد',family_name:'بكير',display_name_format:'first_family',gender:'male',email:'one@example.com',phone:'+962790000001',verification_method:'email'};
check((await call('zameel_complete_registration',[data])).completed,'general registration without university');
check((await db.query('select university,account_type from users where id=$1',[ids[0]])).rows[0].university==='','general receives no invented academic affiliation');
check((await call('zameel_complete_registration',[{...data,first_name:'changed'}])).already_complete,'registration retry preserves completed account');
await as(1);await db.query('update users set onboarding_complete=false where id=$1',[ids[1]]);
await assert.rejects(call('zameel_complete_registration',[{...data,email:'two@example.com',phone:'+962790000002',account_type:'student'}]),/student_details_required/);passed++;
check((await call('zameel_complete_registration',[{...data,email:'two@example.com',phone:'+962790000002',account_type:'student',academic_degree:'bachelor',student_number:'1234',university:'الجامعة الأردنية',college:'كلية الهندسة',major:'هندسة'}])).completed,'student academic details accepted');
await as(0);let st=await call('zameel_trust_state');await call('zameel_trust_state');check(await bal(0)===1000,'initial grant exactly once');
let mid=await start();let view=await call('zameel_trust_state',[mid]);check(!JSON.stringify(view).includes('correct_index')&&!JSON.stringify(view).includes(ids[0]),'current answer and opponent identity hidden');
await as(2);await assert.rejects(call('zameel_trust_state',[mid]),/match_access_denied/);passed++;
await as(0);await call('zameel_trust_chat',[mid,'مرحبا','20000000-0000-4000-8000-000000000001']);await call('zameel_trust_chat',[mid,'مرحبا','20000000-0000-4000-8000-000000000001']);
check((await call('zameel_trust_state',[mid])).messages.length===1,'chat retry idempotent');
await full(mid);await as(0);let first=await call('zameel_trust_decide',[mid,'trust']);check(first.phase==='decision'&&!('opponent_choice' in first),'decision private until both commit');await as(1);let end=await call('zameel_trust_decide',[mid,'trust']);check(end.phase==='finished'&&await bal(0)===1275&&await bal(1)===1275,'trust/trust split 550 and return stakes');
await call('zameel_trust_decide',[mid,'betray']);check(await bal(1)===1275,'settlement retry cannot mint twice');await assert.rejects(call('zameel_trust_chat',[mid,'late','20000000-0000-4000-8000-000000000002']),/match_chat_closed/);passed++;
for (const [c1,c2,b1,b2] of [['betray','trust',1600,950],['trust','betray',950,1600],['betray','betray',950,950]]){await reset();mid=await start();await full(mid);await as(0);await call('zameel_trust_decide',[mid,c1]);await as(1);await call('zameel_trust_decide',[mid,c2]);check(await bal(0)===b1&&await bal(1)===b2,c1+'/'+c2+' balances');}
await reset();mid=await start();await as(0);await call('zameel_trust_leave',[mid]);check(await bal(0)===950&&await bal(1)===1000,'withdrawal forfeits one stake and returns other');
await reset();mid=await start();await db.query("update zameel_trust_matches set seen1=now()-interval '91 seconds' where id=$1",[mid]);await as(1);let lost=await call('zameel_trust_state',[mid]);check(lost.phase==='abandoned'&&await bal(0)===950&&await bal(1)===1000,'90-second unilateral disconnect loses only own stake');
await reset();mid=await start();await db.query("update zameel_trust_matches set seen1=now()-interval '91 seconds',seen2=now()-interval '91 seconds' where id=$1",[mid]);await as(0);check((await call('zameel_trust_state',[mid])).phase==='cancelled'&&await bal(0)===1000&&await bal(1)===1000,'both offline refunded conservatively');
await reset();mid=await start();await db.exec("update zameel_trust_settings set last_sweep_at=now()-interval '151 seconds';update zameel_trust_matches set created_at=now()-interval '180 seconds';");await as(0);check((await call('zameel_trust_state',[mid])).reason==='server_outage'&&await bal(0)===1000&&await bal(1)===1000,'missed server schedule refunds both');
await reset();mid=await start();await db.query("update zameel_trust_matches set deadline=now()-interval '1 second' where id=$1",[mid]);await as(0);let timed=await call('zameel_trust_answer',[mid,1,0]);check(timed.round_no===2&&timed.prize===0,'server deadline expires unanswered round');await as(1);await call('zameel_trust_answer',[mid,1,0]);check((await db.query('select selected2 from zameel_trust_rounds where match_id=$1 and round_no=2',[mid])).rows[0].selected2===null,'stale answer does not answer next round');
await as(0);await assert.rejects(call('zameel_trust_admin_refund',[ids[0],mid,'server issue']),/trust_admin_not_authorized/);passed++;
await call('zameel_trust_admin_refund',[ids[2],mid,'server issue']);await call('zameel_trust_admin_refund',[ids[2],mid,'server issue']);check(await bal(0)===1000&&await bal(1)===1000,'admin refund idempotent');
await as(2);let req='30000000-0000-4000-8000-000000000001';await call('zameel_trust_admin_coins',[ids[2],ids[0],100,'manual reward',req]);await call('zameel_trust_admin_coins',[ids[2],ids[0],100,'manual reward',req]);check(await bal(0)===1100,'admin adjustment request id prevents replay');
const grants=await db.query("select has_function_privilege('authenticated','public.zameel_coin_change(uuid,numeric,text,text,uuid)','execute') as helper,has_table_privilege('authenticated','public.zameel_trust_rounds','select') as answers,has_function_privilege('authenticated','public.zameel_trust_decide(uuid,text)','execute') as decision");check(!grants.rows[0].helper&&!grants.rows[0].answers&&grants.rows[0].decision,'authenticated cannot access ledger helpers or answer tables');

// Failed agreement gives no award; neither answer nor coin events can be replayed.
await reset();mid=await start();await as(0);await call('zameel_trust_answer',[mid,1,1]);await as(1);let wrong=await call('zameel_trust_answer',[mid,1,1]);check(wrong.round_no===2&&wrong.prize===0,'shared wrong answer proceeds without reward');
await as(0);await call('zameel_trust_answer',[mid,2,0]);await as(1);let correct=await call('zameel_trust_answer',[mid,2,0]);await call('zameel_trust_answer',[mid,2,0]);check(correct.prize===20&&(await call('zameel_trust_state',[mid])).prize===20,'correct answer awarded once after replay');
await as(2);await call('zameel_trust_admin_config',[ids[2],2000,75,12]);await as(0);let unchanged=await call('zameel_trust_state',[mid]);check(unchanged.stake===50&&unchanged.reward_unit===10,'new settings never change active match stake or awards');
await db.exec("update feature_flags set is_enabled=false,display_mode='suspended' where feature_key='trust_game';");await as(0);check((await call('zameel_trust_state',[mid])).phase==='cancelled'&&await bal(0)===1000&&await bal(1)===1000,'feature suspension refunds active participants');await assert.rejects(call('zameel_trust_join'),/trust_temporarily_unavailable/);passed++;
await db.exec("update feature_flags set is_enabled=true,display_mode='enabled' where feature_key='trust_game';");
await reset();await as(0);await call('zameel_trust_state');await call('zameel_trust_join');await call('zameel_trust_leave');check(await bal(0)===1000,'queue cancellation never debits coins');
await reset();mid=await start();await full(mid);await as(0);await call('zameel_trust_decide',[mid,'trust']);await call('zameel_trust_decide',[mid,'betray']);await as(1);let irrevocable=await call('zameel_trust_decide',[mid,'trust']);check(irrevocable.phase==='finished'&&await bal(0)===1275,'first secret decision cannot be changed');
await reset();mid=await start();await full(mid);await as(0);await call('zameel_trust_decide',[mid,'trust']);await db.query("update zameel_trust_matches set deadline=now()-interval '1 second' where id=$1",[mid]);let late=await call('zameel_trust_state',[mid]);check(late.phase==='abandoned'&&await bal(0)===1000&&await bal(1)===950,'missing final decision loses stake and grants no question reward');
await reset();mid=await start();await db.query('update zameel_trust_matches set player2=null where id=$1',[mid]);await as(0);check((await call('zameel_trust_state',[mid])).phase==='cancelled'&&await bal(0)===1000,'deleted opponent cancels and refunds remaining player');
// Authentication verification comes from auth.users, not client-provided flags.
await as(2);await db.query('update users set onboarding_complete=false where id=$1',[ids[2]]);
await assert.rejects(call('zameel_complete_registration',[{...data,email:'unverified@example.com',phone:'+962790000003',email_verified:true}]),/verified_contact_required/);passed++;
await db.query("update auth.users set phone='962790000003',phone_confirmed_at=now() where id=$1",[ids[2]]);
check((await call('zameel_complete_registration',[{...data,email:'other@example.com',phone:'+962790000003',verification_method:'phone'}])).completed,'verified phone normalized with or without Auth plus sign');
for (const name of ['20261003180001_133_open_registration.sql','20261003180002_133_trust_game.sql','20261003180003_133_trust_administration.sql'])await db.exec(fs.readFileSync(new URL('../supabase/migrations/'+name,import.meta.url),'utf8'));
check((await db.query('select count(*) as n from zameel_quiz_questions')).rows[0].n===20,'repeat migrations preserve question bank and account data');

// Public promotions preserve post privacy and apply administrative review once.
await db.exec(`grant usage on schema auth to authenticated;
create table posts(id uuid primary key default gen_random_uuid(),user_id uuid references users(id),audience text default 'public',is_hidden boolean default false,text_ar text);
alter table posts enable row level security;
grant select on posts to authenticated;
create policy post_visible on posts for select to authenticated using(audience='public' and not is_hidden and user_id::text<>coalesce(current_setting('test.blocked_owner',true),''));
alter table feature_flags enable row level security;grant select on feature_flags to authenticated;
create policy no_client_flags on feature_flags for select to authenticated using(false);`);
const promotionSQL=fs.readFileSync(new URL('../supabase/migrations/20261003180005_133_post_promotions.sql',import.meta.url),'utf8');
await db.exec(promotionSQL);
const post='40000000-0000-4000-8000-000000000001',privatePost='40000000-0000-4000-8000-000000000002';
await db.query("insert into posts(id,user_id,audience) values($1,$3,'public'),($2,$3,'private')",[post,privatePost,ids[0]]);
await as(0);
let promotion=await call('zameel_request_promotion',[post,7,'طلب تجريبي']);
check(promotion.status==='pending','promotion begins pending review');
check((await call('zameel_request_promotion',[post,7,'retry'])).id===promotion.id,'promotion request retry creates no duplicate');
await assert.rejects(call('zameel_request_promotion',[privatePost,7,'']),/own_public_post_required/);passed++;
await assert.rejects(call('zameel_request_promotion',[post,31,'']),/invalid_promotion_request/);passed++;
await as(1);await assert.rejects(call('zameel_request_promotion',[post,7,'']),/own_public_post_required/);passed++;
await assert.rejects(call('zameel_review_promotion',[ids[1],promotion.id,'approve','valid reason']),/promotion_review_not_authorized/);passed++;
await as(2);await call('zameel_review_promotion',[ids[2],promotion.id,'approve','approved request']);
let firstEnd=(await db.query('select ends_at from zameel_post_promotions where id=$1',[promotion.id])).rows[0].ends_at;
await call('zameel_review_promotion',[ids[2],promotion.id,'approve','approved request']);
check(String((await db.query('select ends_at from zameel_post_promotions where id=$1',[promotion.id])).rows[0].ends_at)===String(firstEnd),'approval retry never extends promotion');
await as(1);await db.exec('set role authenticated');
check((await db.query('select * from zameel_promoted_post_ids()')).rows.length===1,'approved public promotion visible through existing post RLS');
await db.query("select set_config('test.blocked_owner',$1,false)",[ids[0]]);
check((await db.query('select * from zameel_promoted_post_ids()')).rows.length===0,'blocked post owner never bypasses post RLS for promotion');
await db.exec('reset role');await db.query("select set_config('test.blocked_owner','',false)");
await db.query("update posts set audience='private' where id=$1",[post]);
check((await db.query('select status from zameel_post_promotions where id=$1',[promotion.id])).rows[0].status==='cancelled','privacy change cancels promotion immediately');
await db.query("update posts set audience='public' where id=$1",[post]);
await as(1);await db.exec('set role authenticated');check((await db.query('select * from zameel_promoted_post_ids()')).rows.length===0,'making a post public again never revives cancelled promotion');await db.exec('reset role');
await as(0);promotion=await call('zameel_request_promotion',[post,1,'']);await as(2);await call('zameel_review_promotion',[ids[2],promotion.id,'approve','approved again']);
await db.query("update zameel_post_promotions set ends_at=now()-interval '1 second' where id=$1",[promotion.id]);
await as(1);await db.exec('set role authenticated');check((await db.query('select * from zameel_promoted_post_ids()')).rows.length===0,'expired promotions absent from feed');await db.exec('reset role');
await as(0);const nextPromotion=await call('zameel_request_promotion',[post,2,'']);check(nextPromotion.id!==promotion.id,'expired promotion permits a new request');
await as(2);await call('zameel_review_promotion',[ids[2],nextPromotion.id,'reject','request declined']);
await assert.rejects(call('zameel_review_promotion',[ids[2],nextPromotion.id,'approve','cannot revive']),/promotion_already_decided/);passed++;
const permissions=await db.query("select has_table_privilege('authenticated','zameel_post_promotions','insert') as write,has_function_privilege('authenticated','zameel_review_promotion(uuid,uuid,text,text)','execute') as review");
check(!permissions.rows[0].write&&!permissions.rows[0].review,'clients cannot publish promotions or forge administration');
await db.exec(promotionSQL);check((await db.query('select count(*) as n from zameel_quiz_questions')).rows[0].n===20,'promotion migration retry preserves question bank');

await db.exec(`create function can_view_post(uuid,uuid) returns boolean language sql as $$select exists(select 1 from public.posts where id=$2 and audience='public' and not is_hidden and user_id::text<>coalesce(current_setting('test.blocked_owner',true),''))$$;`);
const maintenanceSQL=fs.readFileSync(new URL('../supabase/migrations/20261004100001_135_promotion_targeting_wallet.sql',import.meta.url),'utf8');
console.log("Installing maintenance migration");
try { await db.exec(maintenanceSQL); } catch(e) { console.error("MAINTENANCE SQL FAILURE",e.message,e.code,e.position); throw e; }
await as(0);
const targetArgs=[post,7,'general',true,[],[],18,60,'both','payment test'];
await assert.rejects(call('zameel_request_promotion_v2',targetArgs),/promotion_wallet_not_configured/);passed++;
await as(2);await call('zameel_save_promotion_wallet',[ids[2],'0790000000','Test Beneficiary',true,'initial configuration']);
await as(0);
const paid=await call('zameel_request_promotion_v2',targetArgs);
check(/^[A-Z]{2}\d{4}$/.test(paid.payment_code)&&paid.amount_fils===3500,'reference is two letters and four digits, with server-calculated 500 fils per day');
check((await call('zameel_request_promotion_v2',targetArgs)).payment_code===paid.payment_code,'request retry returns the same payment reference');
await assert.rejects(call('zameel_request_promotion_v2',[post,7,'students',false,['عمّان'],['الجامعة الأردنية'],18,60,'both','']),/invalid_promotion_target/);passed++;
await assert.rejects(call('zameel_request_promotion_v2',[post,7,'general',true,[],[],17,60,'both','']),/invalid_promotion_target/);passed++;
await assert.rejects(call('zameel_request_promotion_v2',[post,7,'general',false,['unknown'],[],18,60,'both','']),/unknown_promotion_location/);passed++;
await as(2);
await assert.rejects(call('zameel_review_promotion',[ids[2],paid.id,'approve','no payment confirmation']),/payment_confirmation_required/);passed++;
await assert.rejects(call('zameel_review_promotion_v2',[ids[2],paid.id,'approve','verify transfer','ZZ0000',3500]),/payment_code_or_amount_mismatch/);passed++;
await assert.rejects(call('zameel_review_promotion_v2',[ids[2],paid.id,'approve','verify transfer',paid.payment_code,500]),/payment_code_or_amount_mismatch/);passed++;
check((await db.query('select payment_verified_at from zameel_post_promotions where id=$1',[paid.id])).rows[0].payment_verified_at===null,'failed confirmation leaves payment unverified');
await call('zameel_review_promotion_v2',[ids[2],paid.id,'approve','matched incoming transfer',paid.payment_code,3500]);
const ends=(await db.query('select ends_at from zameel_post_promotions where id=$1',[paid.id])).rows[0].ends_at;
await call('zameel_review_promotion_v2',[ids[2],paid.id,'approve','matched incoming transfer',paid.payment_code,3500]);
check(String((await db.query('select ends_at from zameel_post_promotions where id=$1',[paid.id])).rows[0].ends_at)===String(ends),'paid approval retry preserves original duration');
await as(1);
check((await db.query('select * from zameel_promoted_post_ids()')).rows.length===0,'unknown age never receives adult-targeted promotion');
await call('zameel_save_audience_profile',['2000-01-01','عمّان','female']);
await db.exec('set role authenticated');
check((await db.query('select * from zameel_promoted_post_ids()')).rows.length===1,'eligible adult receives promotion');
check((await db.query('select payment_code from zameel_post_promotions')).rows.length===0,'viewer cannot read another owner payment reference');
check((await db.query('select user_id from zameel_audience_profiles')).rows.length===1,'viewer can read only own private demographics');
await db.exec('reset role');
await db.query("update zameel_post_promotions set target_gender='male' where id=$1",[paid.id]);
check((await db.query('select * from zameel_promoted_post_ids()')).rows.length===0,'gender filter enforced in database');
await db.query("update zameel_post_promotions set target_gender='both',countrywide=false,target_cities=array['السلط'] where id=$1",[paid.id]);
check((await db.query('select * from zameel_promoted_post_ids()')).rows.length===0,'city filter excludes other cities');
await call('zameel_save_audience_profile',['2000-01-01','السلط','female']);
check((await db.query('select * from zameel_promoted_post_ids()')).rows.length===1,'selected city matches');
await call('zameel_save_audience_profile',['2015-01-01','السلط','female']);
check((await db.query('select * from zameel_promoted_post_ids()')).rows.length===0,'minor does not receive funded campaign');
await call('zameel_save_audience_profile',['2000-01-01','السلط','female']);
await db.query("update zameel_post_promotions set audience_type='students',countrywide=false,target_cities='{}',target_universities=array['الجامعة الأردنية'] where id=$1",[paid.id]);
await db.query("update users set account_type='general',university='الجامعة الأردنية' where id=$1",[ids[1]]);
check((await db.query('select * from zameel_promoted_post_ids()')).rows.length===0,'university campaigns exclude general accounts');
await db.query("update users set account_type='student' where id=$1",[ids[1]]);
check((await db.query('select * from zameel_promoted_post_ids()')).rows.length===1,'student university matches without city restriction');
await db.query("select set_config('test.blocked_owner',$1,false)",[ids[0]]);
check((await db.query('select * from zameel_promoted_post_ids()')).rows.length===0,'new targeted feed preserves canonical post privacy check');
await db.query("select set_config('test.blocked_owner','',false)");
console.log("Installing maintenance migration");
try { await db.exec(maintenanceSQL); } catch(e) { console.error("MAINTENANCE SQL FAILURE",e.message,e.code,e.position); throw e; }
check((await db.query('select payment_code from zameel_post_promotions where id=$1',[paid.id])).rows[0].payment_code===paid.payment_code,'maintenance migration retry preserves payment reference');
await db.exec('set role authenticated');
await assert.rejects(call('zameel_request_promotion',[post,1,'']),/permission denied/);passed++;
await db.exec('reset role');
console.log('DATABASE TESTS PASSED:',passed);



await db.exec(`alter table users add column if not exists cover_image text;alter table users add column if not exists account_privacy text default 'public';alter table posts add column if not exists likes_count integer default 0;alter table posts add column if not exists comments_count integer default 0;
create table if not exists notifications(id uuid primary key default gen_random_uuid(),user_id uuid,actor_id uuid,type text,title_ar text,title_en text,body_ar text,body_en text,data jsonb,is_read boolean default false);
create or replace function zameel_account_can_read() returns boolean language sql as $$select auth.uid() is not null$$;
create or replace function is_blocked(uuid,uuid) returns boolean language sql as $$select coalesce(current_setting('test.photo_block',true),'')='yes'$$;
create or replace function is_colleague(uuid,uuid) returns boolean language sql as $$select false$$;
insert into feature_flags values('comments','Comments','',true,'enabled',100,'global','*') on conflict do nothing;
update users set profile_image='https://example.com/avatar.png',cover_image='https://example.com/cover.png';
grant select,insert,update on users to authenticated;`);
const migration136=fs.readFileSync(new URL('../supabase/migrations/20261004120001_136_profile_performance_photo_reactions.sql',import.meta.url),'utf8');
const verification136=fs.readFileSync(new URL('../supabase/migrations/20261004120002_136_monthly_account_verification.sql',import.meta.url),'utf8');
await db.exec(migration136);await db.exec(verification136);
await as(0);
let photo=await call('zameel_open_profile_photo',[ids[0],'avatar','https://example.com/avatar.png']);
check(photo.id&&(await call('zameel_open_profile_photo',[ids[0],'avatar','https://example.com/avatar.png'])).id===photo.id,'photo interactions have stable identity');
check((await call('zameel_toggle_profile_photo_like',[photo.id])).likes===1,'photo like recorded');
check((await call('zameel_toggle_profile_photo_like',[photo.id])).likes===0,'photo unlike recorded');
await call('zameel_comment_profile_photo',[photo.id,'Nice photo']);
check((await db.query('select count(*) from zameel_profile_photo_comments')).rows[0].count===1,'photo comment persists separately from posts');
await assert.rejects(call('zameel_request_promotion_v2',[photo.id,1,'general',true,[],[],18,60,'both','']),/own_public_post_required/);passed++;
await as(1);
await assert.rejects(call('zameel_open_profile_photo',[ids[0],'avatar','https://evil.example/fake.png']),/profile_photo_unavailable/);passed++;
await db.exec("select set_config('test.photo_block','yes',false)");
await assert.rejects(call('zameel_toggle_profile_photo_like',[photo.id]),/profile_photo_unavailable/);passed++;
await db.exec("set role authenticated");
check((await db.query('select * from zameel_profile_photos')).rows.length===0,'blocked viewer cannot read photo assets through RLS');
check((await db.query('select * from zameel_profile_photo_comments')).rows.length===0,'blocked viewer cannot read photo comments');
await assert.rejects(db.query('insert into zameel_profile_photo_likes(photo_id,user_id) values($1,$2)',[photo.id,ids[1]]),/permission denied/);passed++;
await db.exec("reset role;select set_config('test.photo_block','',false)");
await db.query("update users set account_privacy='private' where id=$1",[ids[0]]);
await assert.rejects(call('zameel_open_profile_photo',[ids[0],'avatar','https://example.com/avatar.png']),/profile_photo_unavailable/);passed++;
await db.query("update users set account_privacy='public',profile_image='https://example.com/new.png' where id=$1",[ids[0]]);
await assert.rejects(call('zameel_toggle_profile_photo_like',[photo.id]),/profile_photo_unavailable/);passed++;
await as(0);
const request=await call('zameel_request_verification');
check(request.amount_fils===1000&&/^[A-Z]{2}\d{4}$/.test(request.payment_code),'monthly verification price and code generated server-side');
check((await call('zameel_request_verification')).id===request.id,'pending verification retry preserves payment receipt');
await as(2);
await assert.rejects(call('zameel_review_verification',[ids[0],request.id,'approve',request.payment_code,1000,'review transfer']),/verification_review_not_authorized/);passed++;
await assert.rejects(call('zameel_review_verification',[ids[2],request.id,'approve',request.payment_code,500,'review transfer']),/payment_code_or_amount_mismatch/);passed++;
await assert.rejects(call('zameel_review_verification',[ids[2],request.id,'approve','ZZ9999',1000,'review transfer']),/payment_code_or_amount_mismatch/);passed++;
const approved=await call('zameel_review_verification',[ids[2],request.id,'approve',request.payment_code,1000,'matched transfer']);
check(approved.status==='approved','verification approval succeeds after exact payment match');
const firstExpiry=approved.ends_at;
check((await db.query("select ends_at=starts_at+interval '1 month' as correct from zameel_verification_requests where id=$1",[request.id])).rows[0].correct,'verification lasts one calendar month');
check((await call('zameel_review_verification',[ids[2],request.id,'approve',request.payment_code,1000,'matched transfer'])).ends_at===firstExpiry,'approval retry cannot extend paid subscription');
check(Number((await db.query("select count(*) from notifications where type='account_verification_review'")).rows[0].count)===1,'verification approval emits exactly one notification');
await as(0);await db.exec('set role authenticated');
await assert.rejects(db.query("update users set verification_expires_at=now()+interval '10 years' where id=$1",[ids[0]]),/verification_admin_required/);passed++;
check((await db.query('select * from zameel_verification_requests')).rows.length===1,'owner reads own verification receipt');
await db.exec('reset role');
const renewal=await call('zameel_request_verification');
check(renewal.id!==request.id&&renewal.payment_code!==paid.payment_code,'renewal creates a distinct payment receipt');
await as(2);
const renewed=await call('zameel_review_verification',[ids[2],renewal.id,'approve',renewal.payment_code,1000,'matched renewal']);
check((await db.query("select ends_at=$1::timestamptz+interval '1 month' as correct from zameel_verification_requests where id=$2",[firstExpiry,renewal.id])).rows[0].correct,'early renewal extends from existing expiry without losing paid days');
await as(1);await db.exec('set role authenticated');
check((await db.query('select * from zameel_verification_requests')).rows.length===0,'another user cannot read payment receipts');
await assert.rejects(call('zameel_review_verification',[ids[2],renewal.id,'approve',renewal.payment_code,1000,'matched renewal']),/permission denied/);passed++;
await db.exec('reset role');
await db.query("update zameel_post_promotions set status='pending',payment_verified_at=now() where id=$1",[paid.id]);
await as(2);await call('zameel_review_promotion',[ids[2],paid.id,'approve','matched transfer']);
await call('zameel_review_promotion',[ids[2],paid.id,'approve','matched transfer']);
check(Number((await db.query("select count(*) from notifications where type='post_promotion_approved'")).rows[0].count)===1,'promotion approval emits one notification despite retry');
await as(1);
check((await db.query('select * from zameel_visible_promotion_badges($1)',[ids[0]])).rows.length===1,'visible profile posts show sponsorship regardless of delivery targeting');
await db.exec(migration136);await db.exec(verification136);
check((await db.query('select verification_expires_at from users where id=$1',[ids[0]])).rows[0].verification_expires_at.toISOString()===new Date(renewed.ends_at).toISOString(),'migration retry preserves verification expiry');
// Release 137: badge privacy and relocated review screen.
await db.exec(`create table zameel_radio_posts(id uuid primary key,user_id uuid,is_anonymous boolean,is_hidden boolean);
create function public.zameel_radio_feed() returns table(id uuid) language sql security definer as $$select id from public.zameel_radio_posts where not is_hidden$$;`);
const migration137=fs.readFileSync(new URL('../supabase/migrations/20261004190001_137_appearance_badges_promotions.sql',import.meta.url),'utf8');
await db.exec(migration137);
check((await db.query("select bool_and(category='promotions') as correct from admin_permissions where permission_key in ('verification.read','verification.manage')")).rows[0].correct,'verification permissions belong to promotions');
await db.exec(`create or replace function admin_can_access_screen(text,uuid) returns boolean language sql as $$select $2='${ids[2]}'::uuid and $1=coalesce(nullif(current_setting('test.screen',true),''),'promotions')$$;`);
await as(2);await db.query("select set_config('test.screen','users',false)");
await assert.rejects(call('zameel_review_verification',[ids[2],renewal.id,'approve',renewal.payment_code,1000,'matched renewal']),/verification_review_not_authorized/);passed++;
await db.query("select set_config('test.screen','promotions',false)");
check((await call('zameel_review_verification',[ids[2],renewal.id,'approve',renewal.payment_code,1000,'matched renewal'])).status==='approved','promotion-screen reviewer can replay without extra charge or extension');
await db.exec(`alter table users enable row level security;create policy badge_profile_visibility on users for select to authenticated using(id=auth.uid());`);
await as(0);await db.exec('set role authenticated');
let badges=await db.query('select * from zameel_verification_badges($1::uuid[])',[[ids[0],ids[1],ids[2]]]);
check(badges.rows.length===1&&badges.rows[0].user_id===ids[0],'badge directory respects profile RLS and returns only active verification');
check((await db.query('select * from zameel_verification_badges($1::uuid[])',[[]])).rows.length===0,'empty badge request returns no rows');
const bounded=[...Array(100).fill(ids[1]),ids[0]];
check((await db.query('select * from zameel_verification_badges($1::uuid[])',[bounded])).rows.length===0,'badge batch is bounded to the first 100 identities');
await db.exec('reset role');await db.query("update users set verification_expires_at=now()-interval '1 second' where id=$1",[ids[0]]);
await db.exec('set role authenticated');
check((await db.query('select * from zameel_verification_badges($1::uuid[])',[[ids[0]]])).rows.length===0,'expired verification is hidden by the server');
await db.exec('reset role');await db.query("update users set verification_expires_at=$1 where id=$2",[renewed.ends_at,ids[0]]);
await db.exec(`insert into zameel_radio_posts values('20000000-0000-4000-8000-000000000001','${ids[0]}',false,false),('20000000-0000-4000-8000-000000000002','${ids[0]}',true,false),('20000000-0000-4000-8000-000000000003','${ids[0]}',false,true);`);
const radios=await db.query("select * from zameel_radio_author_badges(array['20000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000002','20000000-0000-4000-8000-000000000003']::uuid[])");
check(radios.rows.length===1&&radios.rows[0].user_id===ids[0],'radio badge identities exclude anonymous and hidden posts');
await db.exec('set role anon');await assert.rejects(db.query('select * from zameel_verification_badges($1::uuid[])',[[ids[0]]]),/permission denied/);passed++;
await db.exec('reset role');await db.exec(migration137);
check((await db.query('select verification_expires_at from users where id=$1',[ids[0]])).rows[0].verification_expires_at.toISOString()===new Date(renewed.ends_at).toISOString(),'release 137 migration retries preserve paid expiry');
// Release 138: exercise migrations and economic/version boundaries.
await db.exec(`create table app_releases(id uuid primary key default gen_random_uuid(),platform text,version_name text,build_number integer,min_supported_version text,force_update boolean default false,release_notes_ar text default '',is_active boolean default true,created_by uuid,created_at timestamptz default now(),unique(platform,version_name));
alter table posts add column is_deleted_by_admin boolean default false;alter table posts add column media_items jsonb;alter table posts add column image_url text;alter table posts add column video_url text;
create table zameel_post_reports(post_id uuid,status text,reviewed_by uuid,reviewed_at timestamptz,review_reason text);
create table clips(id uuid primary key,user_id uuid,audience text,is_hidden boolean,video_url text);
create function can_view_clip(uuid,uuid) returns boolean language sql as $$select exists(select 1 from clips where id=$2 and audience='public' and not is_hidden)$$;`);
const sql138=[];for(const name of ['20261004210001_138_feed_releases_admin.sql','20261004210002_138_trust_jordan_bot.sql','20261004210003_138_media_download.sql']){
 const sql=fs.readFileSync(new URL('../supabase/migrations/'+name,import.meta.url),'utf8');sql138.push(sql);await db.exec(sql);
}
check((await db.query('select count(*) n from zameel_trust_questions')).rows[0].n===27,'Jordan pool contains 27 independent easy questions');
check((await db.query('select count(*) n from zameel_quiz_questions')).rows[0].n===20,'Jordan pool does not modify quiz questions');
await db.exec("select set_config('test.screen','operations',false)");await as(2);
let release=(await db.query("select id from app_releases where build_number=12")).rows[0].id;
await call('zameel_admin_release_policy',[ids[2],release,true,'https://example.com/update.apk','approved release URL']);
check((await call('zameel_release_policy',['android',12])).allowed===true,'permitted release remains usable');
let latest=(await db.query("select id from app_releases where build_number=13")).rows[0].id;
await call('zameel_admin_release_policy',[ids[2],latest,true,'https://example.com/update.apk','newest release URL']);
await call('zameel_admin_release_policy',[ids[2],release,false,'https://example.com/update.apk','stop previous release']);
check((await call('zameel_release_policy',['android',12])).allowed===false,'stopped build is blocked');
check((await call('zameel_release_policy',['android',13])).allowed===true,'approved current build is allowed');
check((await call('zameel_release_policy',['android',11])).allowed===true,'independent older build can remain allowed');
await as(0);await assert.rejects(call('zameel_admin_release_policy',[ids[0],latest,false,'https://example.com/update.apk','unauthorized change']),/not_authorized/);passed++;
await as(2);await assert.rejects(call('zameel_admin_release_policy',[ids[2],latest,false,'http://example.com','invalid URL']),/invalid_release/);passed++;
await db.exec('set role anon');check((await call('zameel_release_policy',['android',12])).allowed===false,'release policy is available before login');await assert.rejects(call('zameel_trust_start_bot'),/permission denied/);passed++;await db.exec('reset role');
await reset();await as(0);await call('zameel_trust_join');
check((await call('zameel_trust_state')).phase==='waiting','bot does not interrupt the initial human search');
await db.query("update zameel_trust_queue set queued_at=now()-interval '16 seconds' where user_id=$1",[ids[0]]);
let bot=await call('zameel_trust_state');check(bot.is_bot&&bot.phase==='questions'&&bot.opponent_name==='زميل','bot starts after bounded human search and is disclosed');
check(await bal(0)===950,'bot stake debited once');let botId=bot.match_id;
await call('zameel_trust_state',[botId]);check(await bal(0)===950,'bot join/state retry does not debit twice');
check(!JSON.stringify(bot).includes('correct_index'),'bot does not reveal current correct answer');
await as(1);await assert.rejects(call('zameel_trust_state',[botId]),/match_access_denied/);passed++;
await as(0);
for(let round=1;round<=10;round++){
 const actual=(await db.query('select correct_index from zameel_trust_rounds where match_id=$1 and round_no=$2',[botId,round])).rows[0].correct_index;
 await db.query('update zameel_trust_rounds set selected2=$3 where match_id=$1 and round_no=$2',[botId,round,actual]);
 bot=await call('zameel_trust_answer',[botId,round,actual]);
}
check(bot.phase==='decision'&&bot.prize===550,'bot uses the same ten-round reward formula');
await db.query("update zameel_trust_matches set choice2='trust' where id=$1",[botId]);
bot=await call('zameel_trust_decide',[botId,'trust']);check(bot.phase==='finished'&&await bal(0)===1275,'bot trust result returns stake plus half the prize');
await call('zameel_trust_decide',[botId,'betray']);check(await bal(0)===1275,'bot settlement retry cannot mint coins');
check(bot.opponent.name==='زميل'&&bot.opponent.is_bot,'finished bot keeps disclosed identity');
await db.exec("select set_config('test.screen','users',false)");await as(2);
const deletePost=(await db.query('insert into posts(user_id,text_ar) values($1,$2) returning id',[ids[0],'delete test'])).rows[0].id;
await as(0);await assert.rejects(call('zameel_admin_delete_post',[ids[0],deletePost,'users','unauthorized deletion']),/not_authorized/);passed++;
await as(2);await call('zameel_admin_delete_post',[ids[2],deletePost,'users','authorized deletion']);
check((await db.query('select is_hidden,is_deleted_by_admin from posts where id=$1',[deletePost])).rows[0].is_deleted_by_admin,'admin deletion creates permanent moderation tombstone');
const downloadPost=(await db.query('insert into posts(user_id,image_url) values($1,$2) returning id',[ids[0],'https://example.com/image.jpg'])).rows[0].id;
await as(1);const media=await call('zameel_download_media',['post',downloadPost,0]);check(media.type==='image'&&media.owner,'download identity is resolved by server');
await db.query('update posts set is_hidden=true where id=$1',[downloadPost]);await assert.rejects(call('zameel_download_media',['post',downloadPost,0]),/media_unavailable/);passed++;
await db.exec('set role anon');await assert.rejects(call('zameel_download_media',['post',downloadPost,0]),/permission denied/);passed++;await db.exec('reset role');
for(const sql of sql138)await db.exec(sql);
check((await db.query('select count(*) n from zameel_trust_questions')).rows[0].n===27,'migration retry does not duplicate Jordan questions');
check((await call('zameel_release_policy',['android',12])).allowed===false,'migration retry preserves stopped build');

// Bot settlement shares the existing economics for every decision pair.
for (const [mine,theirs,expected] of [['betray','trust',1600],['trust','betray',950],['betray','betray',950]]) {
 await reset(); await as(0); await call('zameel_trust_join');
 await db.query("update zameel_trust_queue set queued_at=now()-interval '16 seconds' where user_id=$1",[ids[0]]);
 const started=await call('zameel_trust_state');
 await db.query("update zameel_trust_matches set phase='decision',prize=550,choice2=$2,deadline=now()+interval '30 seconds' where id=$1",[started.match_id,theirs]);
 await call('zameel_trust_decide',[started.match_id,mine]);
 check(await bal(0)===expected,'bot '+mine+'/'+theirs+' economic result');
 await call('zameel_trust_decide',[started.match_id,mine]);
 check(await bal(0)===expected,'bot '+mine+'/'+theirs+' replay is idempotent');
}
await db.exec(`create or replace function can_view_post(uuid,uuid) returns boolean language sql as $$select exists(select 1 from public.posts where id=$2 and (audience='public' or user_id=$1) and not is_hidden and user_id::text<>coalesce(current_setting('test.blocked_owner',true),''))$$;`);
await db.query('update posts set is_hidden=false,audience=$2 where id=$1',[downloadPost,'private']);
await as(1); await assert.rejects(call('zameel_download_media',['post',downloadPost,0]),/media_unavailable/);passed++;
await as(0);check((await call('zameel_download_media',['post',downloadPost,0])).type==='image','private media downloadable only by its owner');
await db.exec(fs.readFileSync(new URL('../supabase/migrations/20261010160002_151_trust_bot.sql',import.meta.url),'utf8'));
await reset();await as(0);await call('zameel_trust_join');await db.query("update zameel_trust_queue set queued_at=now()-interval '16 seconds' where user_id=$1",[ids[0]]);
const bot151=await call('zameel_trust_state');
let rounds151=(await db.query('select selected1,selected2 from zameel_trust_rounds where match_id=$1',[bot151.match_id])).rows;assert.ok(rounds151.every(x=>x.selected1==null&&x.selected2==null));
await call('zameel_trust_answer',[bot151.match_id,1,3]);
const round151=(await db.query('select selected1,selected2 from zameel_trust_rounds where match_id=$1 and round_no=1',[bot151.match_id])).rows[0];assert.equal(round151.selected1,3);assert.equal(round151.selected2,3);
console.log('PASS: bot waits for human answer and copies selected answer; previous human and settlement tests preserved.');
console.log('ALL DATABASE TESTS PASSED:',passed);await db.close();
