-- Zameel v1.3.8 security hardening.
-- Preserves all product features while closing privilege-escalation and data-leak paths.
-- Safe to run after migrations 001..017.

begin;

-- ---------------------------------------------------------------------------
-- Legacy compatibility: 009 created conversation_members without an id,
-- while later code expects one. Add it idempotently before using it.
-- ---------------------------------------------------------------------------
alter table public.conversation_members
  add column if not exists id uuid;

update public.conversation_members
set id = gen_random_uuid()
where id is null;

alter table public.conversation_members
  alter column id set default gen_random_uuid();
alter table public.conversation_members
  alter column id set not null;

create unique index if not exists conversation_members_id_unique
  on public.conversation_members(id);

-- ---------------------------------------------------------------------------
-- Reusable visibility predicate for post-owned interactions.
-- SECURITY DEFINER is deliberate: it avoids RLS recursion while the function
-- only returns a boolean and exposes no row data.
-- ---------------------------------------------------------------------------
create or replace function public.can_view_post(p_viewer uuid, p_post_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.posts p
    join public.users u on u.id = p.user_id
    where p.id = p_post_id
      and (
        p.user_id = p_viewer
        or (
          not public.is_blocked(p_viewer, p.user_id)
          and (u.account_privacy = 'public' or public.is_colleague(p_viewer, p.user_id))
          and (
            p.audience = 'public'
            or (p.audience = 'friends' and public.is_colleague(p_viewer, p.user_id))
          )
        )
      )
  );
$$;
grant execute on function public.can_view_post(uuid, uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- Users: email is authentication data, not public profile data.
-- The Flutter client no longer selects users.email. Own-account email remains
-- available from Supabase Auth (auth.currentUser.email).
-- ---------------------------------------------------------------------------
revoke select (email) on table public.users from anon, authenticated;

-- ---------------------------------------------------------------------------
-- Graduation invite_token is a bearer secret. It must never be returned by a
-- normal select on a public graduation book.
-- ---------------------------------------------------------------------------
revoke select (invite_token) on table public.graduation_books from anon, authenticated;

create or replace function public.get_graduation_book_invite_token(p_book_id uuid)
returns text
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_token text;
  v_owner uuid;
begin
  if auth.uid() is null then
    raise exception 'not_authenticated';
  end if;

  select owner_id, invite_token
    into v_owner, v_token
  from public.graduation_books
  where id = p_book_id;

  if v_owner is null then
    raise exception 'book_not_found';
  end if;
  if v_owner <> auth.uid() then
    raise exception 'owner_only';
  end if;

  return v_token;
end;
$$;
revoke execute on function public.get_graduation_book_invite_token(uuid) from public, anon;
grant execute on function public.get_graduation_book_invite_token(uuid) to authenticated;

-- Invite joins must also respect blocking, while keeping the invitation feature.
create or replace function public.join_graduation_book(p_book_id uuid, p_token text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_owner uuid;
  v_ok boolean;
begin
  if v_uid is null then raise exception 'not_authenticated'; end if;

  select owner_id, (is_public and allow_writes and invite_token = p_token)
    into v_owner, v_ok
  from public.graduation_books
  where id = p_book_id;

  if coalesce(v_ok, false) = false then
    return false;
  end if;
  if v_owner = v_uid then
    return true;
  end if;
  if public.is_blocked(v_uid, v_owner) then
    raise exception 'blocked_user';
  end if;

  insert into public.graduation_book_members(book_id, user_id)
  values (p_book_id, v_uid)
  on conflict do nothing;

  perform public.ensure_graduation_book_member_pages(p_book_id);
  return true;
end;
$$;
revoke execute on function public.join_graduation_book(uuid,text) from public, anon;
grant execute on function public.join_graduation_book(uuid,text) to authenticated;

-- ---------------------------------------------------------------------------
-- Notifications are server-generated by trusted triggers. Clients may read,
-- mark read and delete their own notifications, but may not forge events for
-- arbitrary recipients.
-- ---------------------------------------------------------------------------
drop policy if exists notifications_insert_authenticated on public.notifications;
revoke insert on table public.notifications from authenticated, anon;

-- ---------------------------------------------------------------------------
-- Post interaction authorization: a user cannot manufacture likes/saves/
-- comments against a private or blocked post by guessing its UUID.
-- ---------------------------------------------------------------------------
drop policy if exists likes_select_authenticated on public.likes;
drop policy if exists likes_insert_self on public.likes;
create policy likes_select_authenticated
on public.likes for select to authenticated
using (public.can_view_post(auth.uid(), post_id));
create policy likes_insert_self
on public.likes for insert to authenticated
with check (user_id = auth.uid() and public.can_view_post(auth.uid(), post_id));

-- Keep self-delete behavior intact.

 drop policy if exists saved_posts_insert_self on public.saved_posts;
create policy saved_posts_insert_self
on public.saved_posts for insert to authenticated
with check (user_id = auth.uid() and public.can_view_post(auth.uid(), post_id));

-- Comments must follow the same visibility as the source post.
drop policy if exists post_comments_select_authenticated on public.post_comments;
drop policy if exists post_comments_insert_self on public.post_comments;
create policy post_comments_select_authenticated
on public.post_comments for select to authenticated
using (public.can_view_post(auth.uid(), post_id));
create policy post_comments_insert_self
on public.post_comments for insert to authenticated
with check (user_id = auth.uid() and public.can_view_post(auth.uid(), post_id));

-- ---------------------------------------------------------------------------
-- Blocking: stop new follows and direct member injection across a block.
-- Existing relationships are preserved; no feature/data is deleted.
-- ---------------------------------------------------------------------------
drop policy if exists follows_insert_self on public.follows;
create policy follows_insert_self
on public.follows for insert to authenticated
with check (
  follower_id = auth.uid()
  and following_id <> auth.uid()
  and not public.is_blocked(auth.uid(), following_id)
);

-- A blocked participant cannot be added to a conversation by the creator.
drop policy if exists conversation_members_self_insert on public.conversation_members;
create policy conversation_members_self_insert
on public.conversation_members for insert to authenticated
with check (
  (
    user_id = auth.uid()
    and exists (
      select 1 from public.conversations c
      where c.id = conversation_id and c.created_by = auth.uid()
    )
  )
  or (
    user_id <> auth.uid()
    and exists (
      select 1 from public.conversations c
      where c.id = conversation_id and c.created_by = auth.uid()
    )
    and not public.is_blocked(auth.uid(), user_id)
  )
);

-- ---------------------------------------------------------------------------
-- Security-definer functions must not be callable anonymously. Authenticated
-- execution remains enabled for the application.
-- ---------------------------------------------------------------------------
revoke execute on function public.delete_my_account() from public, anon;
grant execute on function public.delete_my_account() to authenticated;

revoke execute on function public.ensure_graduation_book(text,text,text,text) from public, anon;
grant execute on function public.ensure_graduation_book(text,text,text,text) to authenticated;

revoke execute on function public.ensure_graduation_book_150_pages(uuid) from public, anon;
grant execute on function public.ensure_graduation_book_150_pages(uuid) to authenticated;

revoke execute on function public.ensure_graduation_book_member_pages(uuid) from public, anon;
grant execute on function public.ensure_graduation_book_member_pages(uuid) to authenticated;

revoke execute on function public.remove_graduation_book_member(uuid,uuid) from public, anon;
grant execute on function public.remove_graduation_book_member(uuid,uuid) to authenticated;

revoke execute on function public.create_direct_conversation(uuid) from public, anon;
grant execute on function public.create_direct_conversation(uuid) to authenticated;

revoke execute on function public.is_blocked(uuid,uuid) from public, anon;
grant execute on function public.is_blocked(uuid,uuid) to authenticated;

revoke execute on function public.is_colleague(uuid,uuid) from public, anon;
grant execute on function public.is_colleague(uuid,uuid) to authenticated;

-- These trigger functions are never intended to be called by API clients.
revoke execute on function public.set_updated_at() from public, anon, authenticated;
revoke execute on function public.handle_new_user() from public, anon, authenticated;
revoke execute on function public.sync_post_shares_count() from public, anon, authenticated;
revoke execute on function public.sync_post_comments_count() from public, anon, authenticated;
revoke execute on function public.sync_post_likes_count() from public, anon, authenticated;
revoke execute on function public.enqueue_notification_for_push() from public, anon, authenticated;
revoke execute on function public.notify_on_message() from public, anon, authenticated;
revoke execute on function public.notify_on_like() from public, anon, authenticated;
revoke execute on function public.notify_on_follow() from public, anon, authenticated;
revoke execute on function public.notify_on_shared_post() from public, anon, authenticated;
revoke execute on function public.notify_on_friend_request() from public, anon, authenticated;
revoke execute on function public.notify_on_friend_request_update() from public, anon, authenticated;
revoke execute on function public.notify_on_post_comment() from public, anon, authenticated;
revoke execute on function public.notify_on_story_reaction() from public, anon, authenticated;
revoke execute on function public.notify_on_clip_comment() from public, anon, authenticated;
revoke execute on function public.notify_on_graduation_book_member() from public, anon, authenticated;

-- Remove already-read notification queue items so a deployment cannot replay
-- historical read notifications as fresh pushes.
delete from public.push_notification_queue q
using public.notifications n
where q.notification_id = n.id
  and n.is_read = true;

commit;
