-- Zameel 028: reliable direct-call signaling + synchronized hangup + story engagement policies.
-- Safe to run after 027_messages_sender_fk_and_call_signaling.sql.

begin;

create table if not exists public.direct_call_sessions (
  room_id text primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  caller_id uuid not null references public.users(id) on delete cascade,
  callee_id uuid not null references public.users(id) on delete cascade,
  with_video boolean not null default true,
  status text not null default 'ringing' check (status in ('ringing','active','ended','declined')),
  created_at timestamptz not null default now(),
  answered_at timestamptz,
  ended_at timestamptz,
  check (caller_id <> callee_id)
);

create index if not exists direct_call_sessions_members_idx
  on public.direct_call_sessions(caller_id, callee_id, created_at desc);

create table if not exists public.call_signals (
  id bigint generated by default as identity primary key,
  room_id text not null references public.direct_call_sessions(room_id) on delete cascade,
  sender_id uuid not null references public.users(id) on delete cascade,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists call_signals_room_created_idx
  on public.call_signals(room_id, created_at);

alter table public.direct_call_sessions enable row level security;
alter table public.call_signals enable row level security;

drop policy if exists direct_call_sessions_member_select on public.direct_call_sessions;
create policy direct_call_sessions_member_select
on public.direct_call_sessions for select to authenticated
using (auth.uid() = caller_id or auth.uid() = callee_id);

drop policy if exists direct_call_sessions_member_update on public.direct_call_sessions;
create policy direct_call_sessions_member_update
on public.direct_call_sessions for update to authenticated
using (auth.uid() = caller_id or auth.uid() = callee_id)
with check (auth.uid() = caller_id or auth.uid() = callee_id);

drop policy if exists call_signals_member_select on public.call_signals;
create policy call_signals_member_select
on public.call_signals for select to authenticated
using (
  exists (
    select 1 from public.direct_call_sessions s
    where s.room_id = call_signals.room_id
      and auth.uid() in (s.caller_id, s.callee_id)
  )
);

drop policy if exists call_signals_member_insert on public.call_signals;
create policy call_signals_member_insert
on public.call_signals for insert to authenticated
with check (
  sender_id = auth.uid()
  and exists (
    select 1 from public.direct_call_sessions s
    where s.room_id = call_signals.room_id
      and auth.uid() in (s.caller_id, s.callee_id)
      and s.status <> 'ended'
  )
);

-- Normalize legacy story_views schemas before installing policies.
-- Some deployed Zameel databases use user_id instead of viewer_id.
do $$
declare
  has_viewer_id boolean;
  has_user_id boolean;
begin
  select exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'story_views' and column_name = 'viewer_id'
  ) into has_viewer_id;

  select exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'story_views' and column_name = 'user_id'
  ) into has_user_id;

  if not has_viewer_id then
    alter table public.story_views add column viewer_id uuid;
    if has_user_id then
      update public.story_views
      set viewer_id = user_id
      where viewer_id is null;
    end if;
  end if;

  -- Keep the FK name stable because the Flutter query uses it as a PostgREST hint.
  if not exists (
    select 1
    from pg_constraint c
    join pg_class t on t.oid = c.conrelid
    join pg_namespace n on n.oid = t.relnamespace
    where n.nspname = 'public'
      and t.relname = 'story_views'
      and c.conname = 'story_views_viewer_id_fkey'
  ) then
    alter table public.story_views
      add constraint story_views_viewer_id_fkey
      foreign key (viewer_id) references public.users(id) on delete cascade not valid;
    alter table public.story_views validate constraint story_views_viewer_id_fkey;
  end if;

  if not exists (select 1 from public.story_views where viewer_id is null) then
    alter table public.story_views alter column viewer_id set not null;
  end if;

  create unique index if not exists story_views_story_viewer_uidx
    on public.story_views(story_id, viewer_id);
end $$;

-- If this is the legacy schema, mirror user_id <-> viewer_id so both old and
-- new application builds continue to work during the transition.
do $$
declare
  has_user_id boolean;
begin
  select exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'story_views' and column_name = 'user_id'
  ) into has_user_id;

  if has_user_id then
    execute $fn$
      create or replace function public.zameel_sync_story_view_user_ids()
      returns trigger
      language plpgsql
      set search_path = public
      as $body$
      begin
        if new.viewer_id is null then
          new.viewer_id := new.user_id;
        end if;
        if new.user_id is null then
          new.user_id := new.viewer_id;
        end if;
        if new.viewer_id is distinct from new.user_id then
          new.user_id := new.viewer_id;
        end if;
        return new;
      end;
      $body$;
    $fn$;

    drop trigger if exists zameel_story_views_sync_ids on public.story_views;
    create trigger zameel_story_views_sync_ids
      before insert or update on public.story_views
      for each row execute function public.zameel_sync_story_view_user_ids();
  end if;
end $$;

-- The owner of a story can inspect viewers/reactions, while viewers retain access
-- to their own engagement rows.
drop policy if exists story_views_self on public.story_views;
drop policy if exists story_views_member_access on public.story_views;
create policy story_views_member_access
on public.story_views for select to authenticated
using (
  viewer_id = auth.uid()
  or exists (
    select 1 from public.social_stories s
    where s.id = story_views.story_id and s.user_id = auth.uid()
  )
);
drop policy if exists story_views_self_write on public.story_views;
create policy story_views_self_write
on public.story_views for insert to authenticated
with check (viewer_id = auth.uid());
drop policy if exists story_views_self_update on public.story_views;
create policy story_views_self_update
on public.story_views for update to authenticated
using (viewer_id = auth.uid()) with check (viewer_id = auth.uid());
drop policy if exists story_views_self_delete on public.story_views;
create policy story_views_self_delete
on public.story_views for delete to authenticated
using (viewer_id = auth.uid());

drop policy if exists story_reactions_self on public.story_reactions;
drop policy if exists story_reactions_member_access on public.story_reactions;
create policy story_reactions_member_access
on public.story_reactions for select to authenticated
using (
  user_id = auth.uid()
  or exists (
    select 1 from public.social_stories s
    where s.id = story_reactions.story_id and s.user_id = auth.uid()
  )
);
drop policy if exists story_reactions_self_insert on public.story_reactions;
create policy story_reactions_self_insert
on public.story_reactions for insert to authenticated
with check (user_id = auth.uid());
drop policy if exists story_reactions_self_update on public.story_reactions;
create policy story_reactions_self_update
on public.story_reactions for update to authenticated
using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists story_reactions_self_delete on public.story_reactions;
create policy story_reactions_self_delete
on public.story_reactions for delete to authenticated
using (user_id = auth.uid());

-- Rebuild direct-call RPC so every invitation creates its durable session before
-- the notification can be delivered.
drop function if exists public.start_direct_call(uuid, uuid, text, boolean);
create function public.start_direct_call(
  other_user_id uuid,
  target_conversation_id uuid,
  target_room_id text,
  with_video boolean default true
)
returns uuid
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
  me uuid := auth.uid();
  caller_name text;
  notification_id uuid;
  allowed boolean;
begin
  if me is null then raise exception 'not_authenticated'; end if;
  if other_user_id is null or other_user_id = me then raise exception 'invalid_partner'; end if;
  if target_conversation_id is null or coalesce(trim(target_room_id), '') = '' then raise exception 'invalid_call_room'; end if;
  if not public.is_conversation_member(target_conversation_id, me)
     or not public.is_conversation_member(target_conversation_id, other_user_id) then
    raise exception 'conversation_membership_required';
  end if;
  if public.is_blocked(me, other_user_id) then raise exception 'blocked_user'; end if;
  if not public.is_colleague(me, other_user_id) then raise exception 'colleague_only'; end if;

  select coalesce(u.allow_calls, true) into allowed from public.users u where u.id = other_user_id;
  if coalesce(allowed, false) = false then raise exception 'calls_disabled'; end if;
  select coalesce(nullif(u.name, ''), 'زميل') into caller_name from public.users u where u.id = me;

  insert into public.direct_call_sessions(room_id, conversation_id, caller_id, callee_id, with_video, status)
  values (target_room_id, target_conversation_id, me, other_user_id, with_video, 'ringing')
  on conflict (room_id) do update set
    conversation_id = excluded.conversation_id,
    caller_id = excluded.caller_id,
    callee_id = excluded.callee_id,
    with_video = excluded.with_video,
    status = 'ringing',
    created_at = now(),
    answered_at = null,
    ended_at = null;

  insert into public.notifications(user_id, actor_id, type, title_ar, title_en, body_ar, body_en, data, is_read)
  values (
    other_user_id, me,
    case when with_video then 'incoming_video_call' else 'incoming_voice_call' end,
    case when with_video then 'مكالمة فيديو واردة' else 'مكالمة صوتية واردة' end,
    case when with_video then 'Incoming video call' else 'Incoming voice call' end,
    caller_name || case when with_video then ' يتصل بك عبر الفيديو' else ' يتصل بك صوتيًا' end,
    caller_name || case when with_video then ' is video calling you' else ' is calling you' end,
    jsonb_build_object('room_id', target_room_id, 'conversation_id', target_conversation_id, 'caller_id', me, 'video', with_video),
    false
  ) returning id into notification_id;

  return notification_id;
end;
$$;
revoke execute on function public.start_direct_call(uuid, uuid, text, boolean) from public, anon;
grant execute on function public.start_direct_call(uuid, uuid, text, boolean) to authenticated;

-- Realtime publication, idempotent.
do $$ begin
  alter publication supabase_realtime add table public.call_signals;
exception when duplicate_object then null; when undefined_object then null;
end $$;
do $$ begin
  alter publication supabase_realtime add table public.direct_call_sessions;
exception when duplicate_object then null; when undefined_object then null;
end $$;

commit;
