-- Zameel 030: durable WebRTC RPC signaling and canonical story engagement.
-- Idempotent and safe to run after migration 029.
begin;

create table if not exists public.call_signals (
  id bigint generated by default as identity primary key,
  room_id text not null references public.direct_call_sessions(room_id) on delete cascade,
  sender_id uuid not null references public.users(id) on delete cascade,
  payload jsonb not null,
  created_at timestamptz not null default now()
);
create index if not exists call_signals_room_id_id_idx on public.call_signals(room_id, id);

drop function if exists public.send_call_signal(text, jsonb);
create function public.send_call_signal(target_room_id text, signal_payload jsonb)
returns bigint
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
  me uuid := auth.uid();
  new_id bigint;
begin
  if me is null then raise exception 'not_authenticated'; end if;
  if not exists (
    select 1 from public.direct_call_sessions s
    where s.room_id = target_room_id
      and me in (s.caller_id, s.callee_id)
      and s.status <> 'ended'
  ) then raise exception 'call_membership_required'; end if;
  insert into public.call_signals(room_id, sender_id, payload)
  values (target_room_id, me, signal_payload)
  returning id into new_id;
  return new_id;
end;
$$;

drop function if exists public.get_call_signals(text, bigint);
create function public.get_call_signals(target_room_id text, after_signal_id bigint default 0)
returns table(signal_id bigint, sender_id uuid, payload jsonb)
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare me uuid := auth.uid();
begin
  if me is null then raise exception 'not_authenticated'; end if;
  if not exists (
    select 1 from public.direct_call_sessions s
    where s.room_id = target_room_id and me in (s.caller_id, s.callee_id)
  ) then raise exception 'call_membership_required'; end if;
  return query
  select c.id, c.sender_id, c.payload
  from public.call_signals c
  where c.room_id = target_room_id and c.id > after_signal_id
  order by c.id
  limit 500;
end;
$$;

revoke execute on function public.send_call_signal(text, jsonb) from public, anon;
revoke execute on function public.get_call_signals(text, bigint) from public, anon;
grant execute on function public.send_call_signal(text, jsonb) to authenticated;
grant execute on function public.get_call_signals(text, bigint) to authenticated;

create table if not exists public.story_view_receipts (
  story_id uuid not null references public.social_stories(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  viewed_at timestamptz not null default now(),
  primary key (story_id, user_id)
);
alter table public.story_view_receipts enable row level security;

drop function if exists public.record_story_view(uuid);
create function public.record_story_view(target_story_id uuid)
returns void
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
  me uuid := auth.uid();
  owner_id uuid;
begin
  if me is null then raise exception 'not_authenticated'; end if;
  select s.user_id into owner_id from public.social_stories s
  where s.id = target_story_id and s.expires_at > now();
  if owner_id is null or owner_id = me then return; end if;
  insert into public.story_view_receipts(story_id, user_id, viewed_at)
  values (target_story_id, me, now())
  on conflict (story_id, user_id) do update set viewed_at = excluded.viewed_at;
end;
$$;

drop function if exists public.get_story_viewers(uuid);
create function public.get_story_viewers(target_story_id uuid)
returns table(user_id uuid, name text, profile_image text, viewed_at timestamptz)
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare me uuid := auth.uid();
begin
  if me is null then raise exception 'not_authenticated'; end if;
  if not exists (select 1 from public.social_stories s where s.id = target_story_id and s.user_id = me)
    then raise exception 'story_owner_required'; end if;
  return query
  select u.id, coalesce(nullif(u.name, ''), 'User')::text, u.profile_image::text, v.viewed_at
  from public.story_view_receipts v join public.users u on u.id = v.user_id
  where v.story_id = target_story_id order by v.viewed_at desc;
end;
$$;

drop function if exists public.get_story_reactions(uuid);
create function public.get_story_reactions(target_story_id uuid)
returns table(user_id uuid, name text, profile_image text, reaction text, created_at timestamptz)
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare me uuid := auth.uid();
begin
  if me is null then raise exception 'not_authenticated'; end if;
  if not exists (select 1 from public.social_stories s where s.id = target_story_id and s.user_id = me)
    then raise exception 'story_owner_required'; end if;
  return query
  select u.id, coalesce(nullif(u.name, ''), 'User')::text, u.profile_image::text,
         r.reaction::text, r.created_at
  from public.story_reactions r join public.users u on u.id = r.user_id
  where r.story_id = target_story_id order by r.created_at desc;
end;
$$;

drop function if exists public.get_story_engagement_counts(uuid);
create function public.get_story_engagement_counts(target_story_id uuid)
returns table(views_count bigint, reactions_count bigint)
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare me uuid := auth.uid();
begin
  if me is null then raise exception 'not_authenticated'; end if;
  if not exists (select 1 from public.social_stories s where s.id = target_story_id)
    then return; end if;
  return query select
    (select count(*) from public.story_view_receipts v where v.story_id = target_story_id),
    (select count(*) from public.story_reactions r where r.story_id = target_story_id);
end;
$$;

revoke execute on function public.record_story_view(uuid) from public, anon;
revoke execute on function public.get_story_viewers(uuid) from public, anon;
revoke execute on function public.get_story_reactions(uuid) from public, anon;
revoke execute on function public.get_story_engagement_counts(uuid) from public, anon;
grant execute on function public.record_story_view(uuid) to authenticated;
grant execute on function public.get_story_viewers(uuid) to authenticated;
grant execute on function public.get_story_reactions(uuid) to authenticated;
grant execute on function public.get_story_engagement_counts(uuid) to authenticated;

commit;
