-- Zameel 033: private transaction chat, optional owner phone, and completion.
-- Run after 032. Safe to execute more than once.
begin;

create table if not exists public.book_listing_contacts (
  listing_id uuid primary key references public.book_listings(id) on delete cascade,
  owner_id uuid not null references public.users(id) on delete cascade,
  phone text not null check (char_length(phone) between 5 and 32),
  created_at timestamptz not null default now()
);

create table if not exists public.book_exchange_messages (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.book_exchange_requests(id) on delete cascade,
  sender_id uuid not null references public.users(id) on delete cascade,
  message_text text not null check (char_length(message_text) between 1 and 1500),
  created_at timestamptz not null default now()
);
create index if not exists book_exchange_messages_request_idx on public.book_exchange_messages(request_id,id);

alter table public.book_listing_contacts enable row level security;
alter table public.book_exchange_messages enable row level security;
drop policy if exists book_contact_owner on public.book_listing_contacts;
create policy book_contact_owner on public.book_listing_contacts for all to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
drop policy if exists book_messages_members_read on public.book_exchange_messages;
create policy book_messages_members_read on public.book_exchange_messages for select to authenticated using(exists(select 1 from public.book_exchange_requests r where r.id=request_id and auth.uid() in(r.owner_id,r.requester_id) and r.status in('accepted','completed')));

create or replace function public.respond_book_exchange(target_request_id uuid, accept_request boolean)
returns void language plpgsql security definer set search_path=public set row_security=off as $$
declare r public.book_exchange_requests; owner_name text;
begin
 select * into r from public.book_exchange_requests where id=target_request_id and owner_id=auth.uid() and status='pending' for update;
 if r.id is null then raise exception 'pending_request_not_found'; end if;
 update public.book_exchange_requests set status=case when accept_request then 'accepted' else 'rejected' end,responded_at=now() where id=r.id;
 select coalesce(nullif(name,''),'زميل') into owner_name from public.users where id=auth.uid();
 insert into public.notifications(user_id,actor_id,type,title_ar,title_en,body_ar,body_en,data,is_read)
 values(r.requester_id,auth.uid(),'book_exchange_response',case when accept_request then 'تم قبول طلب الكتاب' else 'تم رفض طلب الكتاب' end,case when accept_request then 'Book request accepted' else 'Book request rejected' end,owner_name||case when accept_request then ' وافق على طلبك؛ افتح محادثة الكتاب للتنسيق' else ' رفض طلبك' end,owner_name||case when accept_request then ' accepted your request; open the book chat to coordinate' else ' rejected your request' end,jsonb_build_object('request_id',r.id,'listing_id',r.listing_id),false);
end $$;

drop function if exists public.get_book_requests();
create function public.get_book_requests()
returns table(request_id uuid,listing_title text,requester_name text,offered_title text,request_status text,member_role text,created_at timestamptz)
language sql security definer set search_path=public set row_security=off as $$
 select r.id,l.title,coalesce(u.name,'زميل'),o.title,r.status,
   case when r.owner_id=auth.uid() then 'owner'::text else 'requester'::text end,r.created_at
 from public.book_exchange_requests r join public.book_listings l on l.id=r.listing_id
 join public.users u on u.id=r.requester_id left join public.book_listings o on o.id=r.offered_listing_id
 where auth.uid() in(r.owner_id,r.requester_id) order by r.created_at desc;
$$;

drop function if exists public.send_book_request_message(uuid,text);
create function public.send_book_request_message(target_request_id uuid,message_text text)
returns bigint language plpgsql security definer set search_path=public set row_security=off as $$
declare new_id bigint;
begin
 if coalesce(trim(message_text),'')='' then raise exception 'empty_message'; end if;
 if not exists(select 1 from public.book_exchange_requests r where r.id=target_request_id and auth.uid() in(r.owner_id,r.requester_id) and r.status='accepted') then raise exception 'accepted_request_required'; end if;
 insert into public.book_exchange_messages(request_id,sender_id,message_text) values(target_request_id,auth.uid(),trim(message_text)) returning id into new_id;
 return new_id;
end $$;

drop function if exists public.get_book_request_messages(uuid);
create function public.get_book_request_messages(target_request_id uuid)
returns table(message_id bigint,sender_id uuid,message_text text,created_at timestamptz)
language sql security definer set search_path=public set row_security=off as $$
 select m.id,m.sender_id,m.message_text,m.created_at from public.book_exchange_messages m
 where m.request_id=target_request_id and exists(select 1 from public.book_exchange_requests r where r.id=target_request_id and auth.uid() in(r.owner_id,r.requester_id) and r.status in('accepted','completed')) order by m.id;
$$;

drop function if exists public.get_book_request_contact(uuid);
create function public.get_book_request_contact(target_request_id uuid)
returns table(phone text) language sql security definer set search_path=public set row_security=off as $$
 select c.phone from public.book_exchange_requests r join public.book_listing_contacts c on c.listing_id=r.listing_id
 where r.id=target_request_id and auth.uid() in(r.owner_id,r.requester_id) and r.status in('accepted','completed');
$$;

drop function if exists public.complete_book_exchange(uuid);
create function public.complete_book_exchange(target_request_id uuid)
returns void language plpgsql security definer set search_path=public set row_security=off as $$
declare r public.book_exchange_requests;
begin
 select * into r from public.book_exchange_requests where id=target_request_id and auth.uid() in(owner_id,requester_id) and status='accepted' for update;
 if r.id is null then raise exception 'accepted_request_required'; end if;
 update public.book_exchange_requests set status='completed',responded_at=now() where id=r.id;
 update public.book_listings set status='completed',updated_at=now() where id=r.listing_id or id=r.offered_listing_id;
 update public.book_exchange_requests set status='cancelled',responded_at=now() where status='pending' and listing_id=r.listing_id and id<>r.id;
end $$;

revoke execute on function public.get_book_requests(),public.send_book_request_message(uuid,text),public.get_book_request_messages(uuid),public.get_book_request_contact(uuid),public.complete_book_exchange(uuid) from public,anon;
grant execute on function public.get_book_requests(),public.send_book_request_message(uuid,text),public.get_book_request_messages(uuid),public.get_book_request_contact(uuid),public.complete_book_exchange(uuid) to authenticated;
commit;
